B&L QA/objects/Account_Customer_Group__c.object
<CustomObject>
    <description>EMEA. Information on the account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the customer group applies.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Customer Groups</relationshipLabel>
        <relationshipName>Account_Customer_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Customer Group</label>
    <nameField>
        <displayFormat>AccCustomerGroup-{0000000}</displayFormat>
        <label>Account Customer Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Customer Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Account_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP{0000000000}</displayFormat>
        <label>Account Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/BL_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>Current Product Preference</relationshipLabel>
        <relationshipName>B_L_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Current Product Preference</relationshipLabel>
        <relationshipName>B_L_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>B&amp;L Product</label>
    <nameField>
        <displayFormat>BL-PRO-{0000000000}</displayFormat>
        <label>BL Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B&amp;L Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/BL_Sales_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>B&amp;L Sales Histories</relationshipLabel>
        <relationshipName>B_L_Sales_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>B&amp;L Sales Histories</relationshipLabel>
        <relationshipName>B_L_Sales_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>B&amp;L Sales History</label>
    <nameField>
        <displayFormat>BL-SALES-{0000000000}</displayFormat>
        <label>B&amp;L Sales History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B&amp;L Sales Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/AccountProfileCntrl_Test.cls
/**
*  @Class Name:    AccountProfileCntrl_Test
*  @Description:   This is a test class for AccountProfileCntrl
*  @Company:       Standav
*  CreatedDate:    11/01/2018
*
*  Modification Log
*  -----------------------------------------------------------
*  Developer           Modification Date           Comments
*  -----------------------------------------------------------
*  Nitha T S           11/01/2018                  Original Version
*/

@isTest
public class AccountProfileCntrl_Test {
    /**
* Description: This method is to creating Data.
*/
    @testSetup
    static void createData(){
        
        List < Account > acctList = CommonTestDataFactory.createAccounts(1, true);
        
        List < Contact > cntList = CommonTestDataFactory.createContacts(1, true, acctList[0].Id);
        
        List < Opportunity > oppList = CommonTestDataFactory.createOpportunities(1, true, acctList[0].Id);
        
        List < Account_Profile__c > acctProfList = CommonTestDataFactory.createAccountProfiles(1, true, acctList[0].Id);
        
        List < BL_Product__c > blProdList = CommonTestDataFactory.createBLProducts(1, true, acctProfList[0].Id);
        
        List < Account_Customer_Group__c > acctCustGroupList = CommonTestDataFactory.createAccountCustomerGroups(1, true, acctProfList[0].Account__c);
        
        List < BL_Sales_History__c > blSalesHistoryList = CommonTestDataFactory.createBLSalesHistories(1, true, acctProfList[0].Id);
    }
    
    @isTest
    private static void testAccountProfile(){
        Account account = [Select Id, Name From Account where Name = 'Account_0'];
        Account_Profile__c accountProfile = [Select Id, Name, Account__c, RecordTypeId From Account_Profile__c where Account__c = :account.Id];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(accountProfile);
        AccountProfileCntrl testAccPlan = new AccountProfileCntrl(sc);
        Test.stopTest();
    }
}