B&L QA/objects/Account_Contact_Junction__c.object
<CustomObject>
    <description>To allow Contacts to be related to multiple Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account/Contact Relationships</relationshipLabel>
        <relationshipName>Account_Contact_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account/Contact Relationships</relationshipLabel>
        <relationshipName>Account_Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Contact Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account/Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/TestTrgupdateEventWhatAndWhoId.cls
/*
   Credted by     Vijay Singh
   Email          vijay.singh@aequor.com    
*/
@isTest
private class TestTrgupdateEventWhatAndWhoId  {
  static testMethod void testupdateEventWhatAndWhoId() {
    
    Account acc = new Account(Name='test');
    insert acc;
        
    Contact c = new Contact(Accountid=acc.id,LastName='Singh');
    insert c;
    
    Account_Contact_Junction__c obj = new Account_Contact_Junction__c(Account__c=acc.Id,Contact__c=c.Id);
    insert obj ;
    
    Event oEvent1 = new Event();
       
    oEvent1.WhatId = obj.Id; 
    oEvent1.WhoId = c.Id;     
    oEvent1.ActivityDate = date.today();
    oEvent1.StartDateTime = System.now();
    oEvent1.EndDateTime = System.now();
    oEvent1.Type = 'Visit';
    oEvent1.IsReminderSet = false;        
    insert oEvent1;    
    updateEventInfo.updateEventWhatAndWhoId = true;
}
}