B&L QA/objects/Account_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP{0000000000}</displayFormat>
        <label>Account Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Contact_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Profiles</relationshipLabel>
        <relationshipName>Contact_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Profile</label>
    <nameField>
        <displayFormat>CP{0000000000}</displayFormat>
        <label>Contact Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Effectiveness_Summary__c.object
<CustomObject>
    <description>INDSU object to capture the Effectiveness Summary Information</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>INDSU field to capture the date the visits were made on</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Effectiveness Summary</label>
    <nameField>
        <displayFormat>EF{00000000}</displayFormat>
        <label>Effectiveness Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Effectiveness Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Joint_Field_Work__c.object
<CustomObject>
    <description>IndiaSU Object to hold feedback of joint field work done by manager and sales/service executive</description>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>IndiaSU field to collect activity date of the call</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Physician_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Physician Visit</label>
        <referenceTo>Physician_Visit__c</referenceTo>
        <relationshipLabel>Joint Field Work</relationshipLabel>
        <relationshipName>Joint_Field_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IndiaSU field to collect physician who was met during the joint call</description>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Joint Field Work</relationshipLabel>
        <relationshipName>Joint_Field_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Joint Field Work</label>
    <nameField>
        <label>Joint Field Work Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Field Work</pluralLabel>
    <recordTypes>
        <fullName>INDSU</fullName>
        <active>true</active>
        <description>India SU joint field work record type</description>
        <label>INDSU</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Monthly_Implantation_Detail__c.object
<CustomObject>
    <description>APACSU object used to capture and calculate market share for B&amp;L and Competitor Products.</description>
    <fields>
        <fullName>Envista__c</fullName>
        <label>Envista</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Implantation Detail</label>
    <nameField>
        <displayFormat>CP- {00000000}</displayFormat>
        <label>Monthly Implantation Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Implantation Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INDSU Field for getting account profile related data.</description>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>IndiaSU field to collect date on which the activity has occurred</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>APAC CHNSU field:The Contact of the hospital</description>
        <label>Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_time__c</fullName>
        <description>IndiaSU field to collect end description</description>
        <label>End time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Joint_Call_With_ASM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IndiaSU field to identify the call as a joint call with manager</description>
        <label>Joint Call With ASM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key_Driver_1__c</fullName>
        <description>IndiaSU field to collect Key driver products</description>
        <label>Key Driver 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LI61 AO</fullName>
                </value>
                <value>
                    <fullName>LI61AOV</fullName>
                </value>
                <value>
                    <fullName>LI61 SE</fullName>
                </value>
                <value>
                    <fullName>AKREOS</fullName>
                </value>
                <value>
                    <fullName>AKREOS AO</fullName>
                </value>
                <value>
                    <fullName>AKREOS MIL</fullName>
                </value>
                <value>
                    <fullName>Crystalens</fullName>
                </value>
                <value>
                    <fullName>Spares &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Stellaris PC</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Akreos AO Micro Incision Lens</fullName>
                </value>
                <value>
                    <fullName>Akreos Advanced Optics Aspheric Lens</fullName>
                </value>
                <value>
                    <fullName>Akreos Adapt Acrylic Lens</fullName>
                </value>
                <value>
                    <fullName>Silicone LI61AOR Advanced Optics</fullName>
                </value>
                <value>
                    <fullName>Silicone LI61SE Square Edge</fullName>
                </value>
                <value>
                    <fullName>Stellaris Vision Enhancement System</fullName>
                </value>
                <value>
                    <fullName>Envista</fullName>
                </value>
                <value>
                    <fullName>Stellaris/PC</fullName>
                </value>
                <value>
                    <fullName>Millennium</fullName>
                </value>
                <value>
                    <fullName>Protege</fullName>
                </value>
                <value>
                    <fullName>Thermage</fullName>
                </value>
                <value>
                    <fullName>Fraxel</fullName>
                </value>
                <value>
                    <fullName>Vaser</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key_Message_1_CHN__c</fullName>
        <label>Key Message 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Key_Driver_1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivers Benefits of 1.8 mm incision</fullName>
                </value>
                <value>
                    <fullName>Exceptional Vision Quality</fullName>
                </value>
                <value>
                    <fullName>A Proven Track Record Material &amp; Design</fullName>
                </value>
                <value>
                    <fullName>The Akreos AO Lens delivers exceptional vision quality and contrast sensitivity with an aberration-free design</fullName>
                </value>
                <value>
                    <fullName>Innovative design improves clinical outcomes</fullName>
                </value>
                <value>
                    <fullName>Efficient Lens Delivery</fullName>
                </value>
                <value>
                    <fullName>Building On A Proven Track Record</fullName>
                </value>
                <value>
                    <fullName>Biomaterial: Low PCO rate</fullName>
                </value>
                <value>
                    <fullName>Biodesign/Biogeometry: Capsule friendly</fullName>
                </value>
                <value>
                    <fullName>Bioconstruction: Square edge, anti-glare technologies</fullName>
                </value>
                <value>
                    <fullName>Biostability: Clinical and optically stable</fullName>
                </value>
                <value>
                    <fullName>Biomechanics: Foldability, ease of delivery with various implantation techniques</fullName>
                </value>
                <value>
                    <fullName>SofPort AO is an aberration-free aspheric lens for superior vision</fullName>
                </value>
                <value>
                    <fullName>Aberration-free design means no aberrations induced with decentration</fullName>
                </value>
                <value>
                    <fullName>Single-handed, planar delivery of the lens with the fully disposable Easy Load inserter through an unenlarged 2.8-mm phaco incision</fullName>
                </value>
                <value>
                    <fullName>Easy to use for surgeon and staff</fullName>
                </value>
                <value>
                    <fullName>Intelligent IOL technology - 360° posterior square edge; No sloping edge-related glare</fullName>
                </value>
                <value>
                    <fullName>Sub-3 mm insertion</fullName>
                </value>
                <value>
                    <fullName>Planar delivery in the bag</fullName>
                </value>
                <value>
                    <fullName>Total control for surgeon</fullName>
                </value>
                <value>
                    <fullName>Clinical Advantages of 1.8mm MICS</fullName>
                </value>
                <value>
                    <fullName>Stable Chamber Fluidics</fullName>
                </value>
                <value>
                    <fullName>Attune Energy Management System delivering efficient cataract removal with minimal energy</fullName>
                </value>
                <value>
                    <fullName>Ease of Use</fullName>
                </value>
                <value>
                    <fullName>First Time Introduction</fullName>
                </value>
                <value>
                    <fullName>Advanced Fluidics, Cutting and Visualization Technology</fullName>
                </value>
                <value>
                    <fullName>Procedural Flexibility in 1 Integrated System ( Phaco &amp; VR Capabilities )</fullName>
                </value>
                <value>
                    <fullName>Forward thinking design and a footprint that is intuitive</fullName>
                </value>
                <value>
                    <fullName>No Glistenings Observed, Abrasion resistance &amp; Controlled Unfolding</fullName>
                </value>
                <value>
                    <fullName>Wound assisted technology with 2.2mm incision size</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome_1__c</fullName>
        <label>Outcome 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Agree to try</fullName>
                </value>
                <value>
                    <fullName>Agree to increase product usage</fullName>
                </value>
                <value>
                    <fullName>Accept product benefit</fullName>
                </value>
                <value>
                    <fullName>Agreee to further consider</fullName>
                </value>
                <value>
                    <fullName>doubt/negate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IndiaSU field to collect physician from activity</description>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planned Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>IndiaSU field to collect start time of the call</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>APAC SU field to identify the physician visit status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/classes/Trg_setJtCallJtFieldWork_Test.cls
@istest
private class Trg_setJtCallJtFieldWork_Test{

    /**
    * 
    * Test class for 2 triggers event_AU_setJtCallPhysicianVisit and PhysicianVisit_AIBU_CreateEventJtFldWork     
    * 
    * Author              |Author-Email                       |Date        |Comment
    * --------------------|---------------------------------- |------------|----------------------------------------------------
    * Arun David          |arun.david@listertechnologies.com  |11.03.2010  |First Draft
    * Santosh Kumar       |santosh.sriram@listertechnologies.com|10.03.2011|Changing INDSU System Admin to APACSU Admin
    */

    
    static testMethod void JtCallJtFieldWorkTest(){ 

        Profile oProfile = [SELECT Id 
                          FROM profile 
                          WHERE name='INDSU Sales Rep']; //APACSU System Administrator

        UserRole userRole = [Select id from UserRole where UserRole.Name like 'INDSU Sales Rep%' limit 1];
        User oManager = new User(alias = 'mgruser', 
                             email='mgruser@testorg.com', 
                             emailencodingkey='UTF-8',
                             lastname='lastname2',
                             languagelocalekey='en_US', 
                             localesidkey='en_US', 
                             profileid = oProfile.Id, 
                             timezonesidkey='America/Los_Angeles',
                             username='mgruser@testorg.com');
       insert oManager; 
       oManager.lastname='lastname22'; 
       update oManager;
        
        User oUser = new User(alias = 'stduser', 
                             email='stduser@testorg.com', 
                             emailencodingkey='UTF-8',
                             lastname='lastname1',
                             languagelocalekey='en_US', 
                             localesidkey='en_US', 
                             profileid = oProfile.Id, 
                             timezonesidkey='America/Los_Angeles',
                             managerId = oManager.Id,
                             username='stduser@testorg.com',
                             userroleid = userRole.Id
                             );
       insert oUser;  
       oUser.email='stduser@testorg1.com';
        update oUser;
        
        //select a user that has a manager
        //User u = oUser;
        List<User> listIntegrationUser = [Select id from user where Profile.Name = 'BL: Integration User' and isactive = true limit 1] ;
        
        
        Account objAccount = new Account(Name = 'test');
        
        Contact objCon = new Contact();
        
        if(listIntegrationUser.size() > 0){
              system.runAs(listIntegrationUser[0]){
                    objCon.LastName = 'test Contact';
                    objCon.AccountId = objAccount.Id;
                    
                    insert objAccount;
                        
                    insert objCon;
                    
                    AccountTeamMember atm = new AccountTeamMember();
                    atm.AccountId = objAccount.Id;
                    atm.UserId = oUser.Id; 
                    insert atm;
                          
                    Account_Profile__c newAccountProfile = new Account_Profile__c();
                    newAccountProfile.Account__c = objAccount.Id;
                    insert newAccountProfile;
                   
                    Contact_Profile__c cp = new Contact_Profile__c();
                    cp.Contact__c = objCon.Id;
                    insert cp; 
              }
         }
        
        
         
        
        System.runAs(oUser) {

            //choose a valid record type for the trigger to fire
            recordType[] oRecType = [select Id from recordType where sobjecttype = 'Physician_Visit__c' and Name = 'INDSU Sales Planned'];
            
            List<Physician_Visit__c> listPhysicianVisit = new List<Physician_Visit__c>();
            //create a new physician visit
            Physician_Visit__c oPhyVisit = new Physician_Visit__c();
            oPhyVisit.Physician__c = objCon.Id;
            oPhyVisit.recordTypeId = oRecType[0].Id;
            oPhyVisit.Planned_Call__c = true;
            oPhyVisit.OwnerId = oUser.Id;
            oPhyVisit.Start_Time__c = Datetime.Now();
            oPhyVisit.End_Time__c = Datetime.Now();
            oPhyVisit.status__c = 'Open';
            oPhyVisit.Joint_Call_With_ASM__c = false;
            oPhyVisit.Activity_Date__c = Date.today();
            oPhyVisit.Key_Driver_1__c = 'Akreos AO Micro Incision Lens';
            oPhyVisit.Key_Message_1_CHN__c = 'Exceptional Vision Quality';
            oPhyVisit.Outcome_1__c = 'Accept product benefit';
            oPhyVisit.Envista__c = 10;
            oPhyVisit.Expiry_Date__c= Date.Today().addDays(10);
            oPhyVisit.Bundling_Competitor__c = 'Neha';
            oPhyVisit.OT_Hours__c  = true;
            oPhyVisit.Hours_in_Surgery__c = '2';
            oPhyVisit.Doctor_Segmentation__c = 'A';
            listPhysicianVisit.add(oPhyVisit);
            
            Physician_Visit__c oPhyVisit1 = new Physician_Visit__c();
            oPhyVisit1.Physician__c = objCon.Id;
            oPhyVisit1.recordTypeId = oRecType[0].Id;
            oPhyVisit1.Planned_Call__c = true;
            oPhyVisit1.OwnerId = oUser.Id;
            oPhyVisit1.Start_Time__c = Datetime.Now();
            oPhyVisit1.End_Time__c = Datetime.Now();
            oPhyVisit1.status__c = 'Open';
            oPhyVisit1.Joint_Call_With_ASM__c = false;
            oPhyVisit1.Activity_Date__c = Date.today();
            oPhyVisit1.Key_Driver_1__c = 'Akreos AO Micro Incision Lens';
            oPhyVisit1.Key_Message_1_CHN__c = 'Exceptional Vision Quality';
            oPhyVisit1.Outcome_1__c = 'Accept product benefit';
            oPhyVisit1.Envista__c = 10;
            oPhyVisit1.Expiry_Date__c= Date.Today().addDays(10);
            oPhyVisit1.Bundling_Competitor__c = 'Neha';
            oPhyVisit1.OT_Hours__c  = true;
            oPhyVisit1.Hours_in_Surgery__c = '2';
            oPhyVisit1.Doctor_Segmentation__c = 'B';
            listPhysicianVisit.add(oPhyVisit1);
            
            Physician_Visit__c oPhyVisit2 = new Physician_Visit__c();
            oPhyVisit2.Physician__c = objCon.Id;
            oPhyVisit2.recordTypeId = oRecType[0].Id;
            oPhyVisit2.Planned_Call__c = true;
            oPhyVisit2.OwnerId = oUser.Id;
            oPhyVisit2.Start_Time__c = Datetime.Now();
            oPhyVisit2.End_Time__c = Datetime.Now();
            oPhyVisit2.status__c = 'Open';
            oPhyVisit2.Joint_Call_With_ASM__c = false;
            oPhyVisit2.Activity_Date__c = Date.today();
            oPhyVisit2.Key_Driver_1__c = 'Akreos AO Micro Incision Lens';
            oPhyVisit2.Key_Message_1_CHN__c = 'Exceptional Vision Quality';
            oPhyVisit2.Outcome_1__c = 'Accept product benefit';
            oPhyVisit2.Envista__c = 10;
            oPhyVisit2.Expiry_Date__c= Date.Today().addDays(10);
            oPhyVisit2.Bundling_Competitor__c = 'Neha';
            oPhyVisit2.OT_Hours__c  = true;
            oPhyVisit2.Hours_in_Surgery__c = '2';
            oPhyVisit2.Doctor_Segmentation__c = 'C';
            listPhysicianVisit.add(oPhyVisit2);
            
            Physician_Visit__c oPhyVisit3 = new Physician_Visit__c();
            oPhyVisit3.Physician__c = objCon.Id;
            oPhyVisit3.recordTypeId = oRecType[0].Id;
            oPhyVisit3.Planned_Call__c = true;
            oPhyVisit3.OwnerId = oUser.Id;
            oPhyVisit3.Start_Time__c = Datetime.Now();
            oPhyVisit3.End_Time__c = Datetime.Now();
            oPhyVisit3.status__c = 'Open';
            oPhyVisit3.Joint_Call_With_ASM__c = false;
            oPhyVisit3.Activity_Date__c = Date.today();
            oPhyVisit3.Key_Driver_1__c = 'Akreos AO Micro Incision Lens';
            oPhyVisit3.Key_Message_1_CHN__c = 'Exceptional Vision Quality';
            oPhyVisit3.Outcome_1__c = 'Accept product benefit';
            oPhyVisit3.Envista__c = 10;
            oPhyVisit3.Expiry_Date__c= Date.Today().addDays(10);
            oPhyVisit3.Bundling_Competitor__c = 'Neha';
            oPhyVisit3.OT_Hours__c  = true;
            oPhyVisit3.Hours_in_Surgery__c = '2';
            oPhyVisit3.Doctor_Segmentation__c = 'D';
            listPhysicianVisit.add(oPhyVisit3);
            
            
            insert listPhysicianVisit; 
            
            oPhyVisit.status__c = 'Completed';
            oPhyVisit1.status__c = 'Completed';
            oPhyVisit2.status__c = 'Completed';
            oPhyVisit3.status__c = 'Completed';
            
            update listPhysicianVisit;
            //---------------------
            oPhyVisit.Planned_Call__c = false;
            oPhyVisit.Doctor_Segmentation__c = 'A';
           
            
            oPhyVisit1.Planned_Call__c = false;
            oPhyVisit1.Doctor_Segmentation__c = 'B';
           
            
            oPhyVisit2.Planned_Call__c = false;
            oPhyVisit2.Doctor_Segmentation__c = 'C';
             
             
            oPhyVisit3.Planned_Call__c = false;
            oPhyVisit3.Doctor_Segmentation__c = 'D';
            
            clsPhysicianVisitUpdate.isInsert = false; 
            update listPhysicianVisit;
           
            
            Monthly_Implantation_Detail__c monthlyImplantation = new Monthly_Implantation_Detail__c();
            monthlyImplantation.Physician_Name__c = objCon.Id;
            monthlyImplantation.Month__c = String.ValueOf(oPhyVisit.Activity_Date__c.Month());
            monthlyImplantation.Year__c = oPhyVisit.Activity_Date__c.Year();
            insert monthlyImplantation;
            
            oPhyVisit.Joint_Call_With_ASM__c = true; 
            oPhyVisit.status__c = 'Completed';
            clsPhysicianVisitUpdate.isInsert = false;
            oPhyVisit.Hours_in_Surgery__c = '5';
            oPhyVisit.Call_Objective_Achieved__c = true;
            
            oPhyVisit1.Joint_Call_With_ASM__c = true; 
            oPhyVisit1.status__c = 'Completed';
            //clsPhysicianVisitUpdate.isInsert = false;
            oPhyVisit1.Hours_in_Surgery__c = '1';
            oPhyVisit1.Call_Objective_Achieved__c = true;
            
            oPhyVisit2.status__c = 'Completed';
            oPhyVisit2.Call_Objective_Achieved__c = true;
            
            oPhyVisit3.status__c = 'Completed';
            oPhyVisit3.Call_Objective_Achieved__c = true;
            
            update listPhysicianVisit;
            
            Effectiveness_Summary__c effectivenessSummary = new Effectiveness_Summary__c();
            effectivenessSummary.Date__c = oPhyVisit.Activity_Date__c;
            effectivenessSummary.ownerId = oPhyVisit.OwnerId;            
            effectivenessSummary.OT_Hours__c = 3;
            
            
            insert effectivenessSummary ;
            
           
            
           
            
            /*oPhyVisit.Hours_in_Surgery__c = '3';
            oPhyVisit.Doctor_Segmentation__c = 'B';
            update oPhyVisit;*/
           /* try {  
                update oPhyVisit;
            }
            catch(exception e)

{
System.debug(Logginglevel.ERROR, 'ERROR: ' + e.getMessage() );
} */

            //query the event that was created as a result of insertion of a physician visit
            Event oEvt = [Select Join_Call__c from Event where Physician_Visit_Id__c = :oPhyVisit.Id];
            
            oEvt.Join_Call__c = true;

            //update the event to mark it as joint call to fire the event trigger
            update oEvt;
            
            clsPhysicianVisitUpdate.blnIsTriggerFiredAlreadyForJntFldWrk = false;
            
            //oPhyVisit.status__c = 'Completed';
            //oPhyVisit.Joint_Call_With_ASM__c = true;

            //update the physician vist to objetive achieved so that the update trigger fires
            //update oPhyVisit;
            
            
        }           
    }
    static testMethod void JtCallJtFieldWorkTest1(){
        
    //  Joint_Field_Work__c jtFldWork = new Joint_Field_Work__c();
        
    //  insert jtFldWork;
        
         
    }
    
}