B&L QA/objects/Account_Customer_Group__c.object
<CustomObject>
    <description>EMEA. Information on the account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the customer group applies.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Customer Groups</relationshipLabel>
        <relationshipName>Account_Customer_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Group_Type__c</fullName>
        <description>Group type (i.e. PRC)</description>
        <label>Customer Group Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <description>Account customer group value.</description>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Customer Group</label>
    <nameField>
        <displayFormat>AccCustomerGroup-{0000000}</displayFormat>
        <label>Account Customer Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Customer Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Account_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP{0000000000}</displayFormat>
        <label>Account Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <recordTypes>
        <fullName>Cataract</fullName>
        <active>true</active>
        <description>Account Profile Information For Cataract</description>
        <label>Cataract</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retina</fullName>
        <active>true</active>
        <description>Retina Based Information For Account Profile</description>
        <label>Retina</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/BL_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>Current Product Preference</relationshipLabel>
        <relationshipName>B_L_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Current Product Preference</relationshipLabel>
        <relationshipName>B_L_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Volume__c</fullName>
        <label>Annual Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Equipment_Age__c</fullName>
        <label>Equipment Age (Years)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retina</fullName>
                </value>
                <value>
                    <fullName>Cataract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Laser Probe</fullName>
                </value>
                <value>
                    <fullName>DDMS</fullName>
                </value>
                <value>
                    <fullName>Soft tip</fullName>
                </value>
                <value>
                    <fullName>Oil</fullName>
                </value>
                <value>
                    <fullName>Disp Inst</fullName>
                </value>
                <value>
                    <fullName>Pack,  Needle, IA</fullName>
                </value>
                <value>
                    <fullName>Monofocal IOL</fullName>
                </value>
                <value>
                    <fullName>PIOL</fullName>
                </value>
                <value>
                    <fullName>Toric IOL</fullName>
                </value>
                <value>
                    <fullName>OVD</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>B&amp;L Product</label>
    <nameField>
        <displayFormat>BL-PRO-{0000000000}</displayFormat>
        <label>BL Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B&amp;L Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/BL_Sales_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>B&amp;L Sales Histories</relationshipLabel>
        <relationshipName>B_L_Sales_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>B&amp;L Sales Histories</relationshipLabel>
        <relationshipName>B_L_Sales_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Date__c</fullName>
        <label>Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <label>Sales Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Laser Probe</fullName>
                </value>
                <value>
                    <fullName>DDMS</fullName>
                </value>
                <value>
                    <fullName>Soft tip</fullName>
                </value>
                <value>
                    <fullName>Sil OIL</fullName>
                </value>
                <value>
                    <fullName>Pinnacle</fullName>
                </value>
                <value>
                    <fullName>Eq Disposable</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>IOL</fullName>
                </value>
                <value>
                    <fullName>OVD</fullName>
                </value>
                <value>
                    <fullName>Instruments</fullName>
                </value>
                <value>
                    <fullName>Custom Pack</fullName>
                </value>
                <value>
                    <fullName>Crystalens</fullName>
                </value>
                <value>
                    <fullName>Trulign</fullName>
                </value>
                <value>
                    <fullName>EnVista</fullName>
                </value>
                <value>
                    <fullName>Akreos</fullName>
                </value>
                <value>
                    <fullName>SofPort</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
                <value>
                    <fullName>Cap Guard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Sales__c</fullName>
        <label>Total Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>B&amp;L Sales History</label>
    <nameField>
        <displayFormat>BL-SALES-{0000000000}</displayFormat>
        <label>B&amp;L Sales History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B&amp;L Sales Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/AccountProfileCntrl.cls
/**
*  @Class Name:    AccountProfileCntrl
*  @Description:   This class is the data provider for Account_Profile_Information_vf pdf page
*  @Company:       Standav
*  CreatedDate:    09/Jan/2018
*
*  Modification Log
*  -----------------------------------------------------------
*  Developer             Modification Date           Comments
*  -----------------------------------------------------------
*  Aman Sawhney          10/Jan/2018                  Original Version
*/
public with sharing class AccountProfileCntrl {
    
    /* variables for the account and its related list
information on the vf page named Account_Profile_Information_vf*/
    
    public Account_Profile__c accountProfile{get;set;}
    public Account accountInfo{get;set;}
    public List<contact> allContactList{get;set;}
    public List<contact> keyDecisionMakerList{get;set;}
    public List<BL_Product__c> blPrductList{get;set;}
    public List<AccountTeamMember> accountTeamList{get;set;}
    public List<BL_Sales_History__c> salesHistoryList{get;set;}
    public List<Account_Customer_Group__c> customerGroupList{get;set;}
    public List<Opportunity> opportunityList{get;set;}
    
    
    //constructor initialization
    public AccountProfileCntrl(ApexPages.StandardController controller) {
        
        //target account profile
        accountProfile = (Account_Profile__c)controller.getRecord();
        
        accountProfile  = [select Id,Account__c,RecordType.Name from Account_Profile__c where Id=:accountProfile.Id];
        
        //if the account entry on this account profile is filled
        if(accountProfile.Account__c !=null){
            
            //fetch the account info
            accountInfo = [select Id,Name,BillingCity,BillingStreet,BillingState from Account where Id=:accountProfile.Account__c];
            
            //fetch all the related list of account
            allContactList = [select Id,Name,External__c,Key_Decision_Maker__c,Contact_Role__c,Contact_Title__c,Sphere_of_Influence__c  
                              from Contact where AccountId=:accountProfile.Account__c];
            
            //fetch BL Product for family retina or cataract
            String productFamily = accountProfile.RecordType.Name;
            
            blPrductList = [select Id,Name,Type__c,Price__c,Equipment_Age__c,Annual_Volume__c from BL_Product__c where Account_Profile__c=:accountProfile.Id
                            AND Product_Family__c=:productFamily];
            
            
            accountTeamList = [select Id,TeamMemberRole,User.Name,AccountAccessLevel,CaseAccessLevel,ContactAccessLevel,OpportunityAccessLevel
                               from AccountTeamMember where AccountId=:accountProfile.Account__c];
            
            
            customerGroupList= [select Id,Name,Customer_Group__c,Customer_Group_Type__c from Account_Customer_Group__c where Account__c=:accountProfile.Account__c];
            
            salesHistoryList= [select Id,Sales_Date__c,Sales_Type__c,Total_Sales__c from BL_Sales_History__c where Account_Profile__c=:accountProfile.Id];
            
            opportunityList = [select Id,Name,StageName,Amount,CloseDate from Opportunity where AccountId=:accountProfile.Account__c];
            
            //fill key decision maker list
            keyDecisionMakerList = new List<contact>();
            for(contact c: allContactList){
                
                if(c.Key_Decision_Maker__c){
                    
                    keyDecisionMakerList.add(c);
                    
                }
            }
        }
    }
}