B&L QA/objects/Account_Customer_Group__c.object
<CustomObject>
    <description>EMEA. Information on the account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the customer group applies.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Customer Groups</relationshipLabel>
        <relationshipName>Account_Customer_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Group_Type__c</fullName>
        <description>Group type (i.e. PRC)</description>
        <label>Customer Group Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <description>Account customer group value.</description>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Customer Group</label>
    <nameField>
        <displayFormat>AccCustomerGroup-{0000000}</displayFormat>
        <label>Account Customer Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Customer Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Account_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP{0000000000}</displayFormat>
        <label>Account Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <recordTypes>
        <fullName>Cataract</fullName>
        <active>true</active>
        <description>Account Profile Information For Cataract</description>
        <label>Cataract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/BL_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>Current Product Preference</relationshipLabel>
        <relationshipName>B_L_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Current Product Preference</relationshipLabel>
        <relationshipName>B_L_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Volume__c</fullName>
        <label>Annual Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Equipment_Age__c</fullName>
        <label>Equipment Age (Years)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Product Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Laser Probe</fullName>
                </value>
                <value>
                    <fullName>DDMS</fullName>
                </value>
                <value>
                    <fullName>Soft tip</fullName>
                </value>
                <value>
                    <fullName>Oil</fullName>
                </value>
                <value>
                    <fullName>Disp Inst</fullName>
                </value>
                <value>
                    <fullName>Pack,  Needle, IA</fullName>
                </value>
                <value>
                    <fullName>Monofocal IOL</fullName>
                </value>
                <value>
                    <fullName>PIOL</fullName>
                </value>
                <value>
                    <fullName>Toric IOL</fullName>
                </value>
                <value>
                    <fullName>OVD</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>B&amp;L Product</label>
    <nameField>
        <displayFormat>BL-PRO-{0000000000}</displayFormat>
        <label>BL Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B&amp;L Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/BL_Sales_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>B&amp;L Sales Histories</relationshipLabel>
        <relationshipName>B_L_Sales_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>B&amp;L Sales Histories</relationshipLabel>
        <relationshipName>B_L_Sales_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Date__c</fullName>
        <label>Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <label>Sales Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Laser Probe</fullName>
                </value>
                <value>
                    <fullName>DDMS</fullName>
                </value>
                <value>
                    <fullName>Soft tip</fullName>
                </value>
                <value>
                    <fullName>Sil OIL</fullName>
                </value>
                <value>
                    <fullName>Pinnacle</fullName>
                </value>
                <value>
                    <fullName>Eq Disposable</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>IOL</fullName>
                </value>
                <value>
                    <fullName>OVD</fullName>
                </value>
                <value>
                    <fullName>Instruments</fullName>
                </value>
                <value>
                    <fullName>Custom Pack</fullName>
                </value>
                <value>
                    <fullName>Crystalens</fullName>
                </value>
                <value>
                    <fullName>Trulign</fullName>
                </value>
                <value>
                    <fullName>EnVista</fullName>
                </value>
                <value>
                    <fullName>Akreos</fullName>
                </value>
                <value>
                    <fullName>SofPort</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
                <value>
                    <fullName>Cap Guard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Sales__c</fullName>
        <label>Total Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>B&amp;L Sales History</label>
    <nameField>
        <displayFormat>BL-SALES-{0000000000}</displayFormat>
        <label>B&amp;L Sales History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B&amp;L Sales Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/CommonTestDataFactory.cls
/**
*  Class Name: CommonTestDataFactory  
*  Description: This is a TestDataUtil class for creating Object Records.
*  Company: Standav
*  CreatedDate:11/01/2018
*
*  Modification Log
*  -----------------------------------------------------------
*  Developer           Modification Date           Comments
*  -----------------------------------------------------------  
*  Nitha T S             11/01/2018              Original version
*/
public class CommonTestDataFactory {
    public static String PROFILE_SYSTEM_ADMINISTRATOR = 'System Administrator';
    public static String PROFILE_STANDARD_PLATFORM_USER = 'Standard Platform User';
    public static String PROFILE_STANDARD_PLATFORM_ONE_APP_USER = 'Standard Platform One App User';
    public static String PROFILE_STANDARD_USER = 'Standard User';
    public static String PROFILE_PARTNER_USER = 'Partner User';
    public static String PROFILE_HIGH_VOLUME_CUSTOMER_PORTAL = 'High Volume Customer Portal';
    public static String PROFILE_AUTHENTICATED_WEBSITE = 'Authenticated Website';
    public static String PROFILE_CUSTOMER_PORTAL_USER = 'Customer Portal User';
    public static String PROFILE_CUSTOMER_PORTAL_MANAGER = 'Customer Portal Manager';
    public static String PROFILE_SOLUTION_MANAGER = 'Solution Manager';
    public static String PROFILE_MARKETING_USER = 'Marketing User';
    public static String PROFILE_CONTRACT_MANAGER = 'Contract Manager';
    public static String PROFILE_SALES_BDR_SBDR = 'Sales BDR/SBDR';
    public static String PROFILE_SALES_REP = 'Sales Rep';
    public static String PROFILE_READ_ONLY = 'Read Only';
    public static String PROFILE_CHATTER_ONLY_USER = 'Chatter OnlyUser';
    public static String PROFILE_CHATTER_FREE_USER = 'Chatter FreeUser';
    public static String PROFILE_CHATTER_EXTERNAL_USER = 'Chatter External User';
    public static String PROFILE_CHATTERMODERATOR_USER = 'Chatter Moderator User';
    public static String PROFILE_SITE_COM_ONLY_USER = 'Site.com Only User';
    public static String PROFILE_GOLD_ADMIN = 'Gold Partner - Administrator';
    public static String PROFILE_GOLD_SALES = 'Gold Partner - Sales';
    public static String PROFILE_GOLD_MARKETING = 'Gold Partner - Marketing';
    public static String PROFILE_GOLD_CONTENT = 'Gold Partner - Content';
    public static String PROFILE_GOLD_MDF = 'Gold Partner - MDF';
    
    private static Integer usersCreated = 0;
    public static final String TEST_OPP_NAME = 'Test Opp';
    public static final String TEST_OPP_TYPE = 'Initial Business';
    public static final String TEST_OPP_STAGE = '1 - Partner Oppty';
    
    // create Contact records
    public static List < Contact > createContacts(Integer numToInsert, boolean doInsert, Id accountId) {
        List < Contact > cts = new List < Contact > ();
        for (Integer i = 0; i < numToInsert; i++) {
            Contact c = new Contact(
                LastName = 'Contact_' + i,
                Phone = '999-555-' + 1000 + i,
                Email = 'examplecontact_' + i + '@example.com',
                AccountId = accountId,
                Key_Decision_Maker__c = true
            );
            cts.add(c);
        }
        if (doInsert) {
            insert cts;
        }
        return cts;
    }
    
    // create Account records
    public static List < Account > createAccounts(Integer numToInsert, boolean doInsert) {
        List < Account > acnts = new List < Account > ();
        for (Integer i = 0; i < numToInsert; i++) {
            Account acnt = new Account(
                Name = 'Account_' + i,
                Phone = '999-999-' + (1000 + i),
                BillingCountry = 'United States',
                BillingPostalcode = 'LS1 3DD',
                BillingState = 'CA',
                BillingCity = 'San Francisco',
                BillingStreet = '111 Some Rd',
                Industry = 'High Technology'
            );
            acnts.add(acnt);
        }
        
        if (doInsert) {
            insert acnts;
        }
        return acnts;    
    }
    
    // create Opportunity records
    public static List < Opportunity > createOpportunities(Integer numToInsert, boolean doInsert, Id accountId) {
        List < Opportunity > oppList = new List < Opportunity > ();
        for (Integer i = 0; i < numToInsert; i++) {
            oppList.add(new Opportunity(
                Name = 'Opportunity_' + i,
                CloseDate = Date.today().addDays(7),
                StageName = '1 - Open Qualified',
                AccountId = accountId
            ));
        }
        if (doInsert) {
            insert oppList;
        }
        return oppList;
    }
    
    // create User records
    /*public static List < User > createUsers(Integer numToInsert, Boolean doInsert) {
        List < User > users = new List < User > ();
        for (Integer i = 0; i < numToInsert; i++) {
            User user = new User(
                LastName = 'LastName_' + i,
                Alias = ((usersCreated++) + 'User_' + i).left(8),
                Email = 'test_' + i + '@gmail.com',
                UserName = (usersCreated++) + 'testcaseuser_' + i + '@gmail.com',
                CommunityNickname = (usersCreated++) + 'NickName_' + i,
                Department = 'Some Department',
                EmailEncodingKey = 'ISO-8859-1',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                IsActive = true);
            users.add(user);
        }
        if (doInsert) {
            insert users;
        }
        return users;
    }*/
    
    // create Account_Profile__c records
    public static List < Account_Profile__c > createAccountProfiles(Integer numToInsert, Boolean doInsert, Id accountId) {
        List < Account_Profile__c > accountProfiles = new List < Account_Profile__c > ();
        for (Integer i = 0; i < numToInsert; i++) {
            Account_Profile__c acctProf = new Account_Profile__c(
                Account__c = accountId,
                RecordTypeId = Schema.SObjectType.Account_Profile__c.getRecordTypeInfosByName().get('Cataract').getRecordTypeId()
            );
            accountProfiles.add(acctProf);
        }
        if (doInsert) {
            insert accountProfiles;
        }
        return accountProfiles;
    }
    
    // create BL_Product__c records
    public static List < BL_Product__c > createBLProducts(Integer numToInsert, Boolean doInsert, Id accountProfId) {
        List < BL_Product__c > blProducts = new List < BL_Product__c > ();
        for (Integer i = 0; i < numToInsert; i++) {
            BL_Product__c blProd = new BL_Product__c(
                Type__c = 'Equipment',
                Price__c = 54.00,
                Equipment_Age__c = 2,
                Annual_Volume__c = 300,
                Account_Profile__c = accountProfId,
                Product_Name__c = 'test Product Name'
            );
            blProducts.add(blProd);
        }
        if (doInsert) {
            insert blProducts;
        }
        return blProducts;
    }
    
    // create Account_Customer_Group__c records
    public static List < Account_Customer_Group__c > createAccountCustomerGroups(Integer numToInsert, Boolean doInsert, Id accountId) {
        List < Account_Customer_Group__c > acctCustGroups = new List < Account_Customer_Group__c > ();
        for (Integer i = 0; i < numToInsert; i++) {
            Account_Customer_Group__c acctCustGroup = new Account_Customer_Group__c(
                Customer_Group__c = 'test Customer Group',
                Customer_Group_Type__c = 'test Customer Group Type',
                Account__c = accountId
            );
            acctCustGroups.add(acctCustGroup);
        }
        if (doInsert) {
            insert acctCustGroups;
        }
        return acctCustGroups;
    }
    
    // create BL_Sales_History__c records
    public static List < BL_Sales_History__c > createBLSalesHistories(Integer numToInsert, Boolean doInsert, Id accountProfId) {
        List < BL_Sales_History__c > blSalesHistories = new List < BL_Sales_History__c > ();
        for (Integer i = 0; i < numToInsert; i++) {
            BL_Sales_History__c blSalesHistory = new BL_Sales_History__c(
                Sales_Date__c = system.today(),
                Sales_Type__c = 'Equipment',
                Total_Sales__c = 236.00,
                Account_Profile__c = accountProfId
            );
            blSalesHistories.add(blSalesHistory);
        }
        if (doInsert) {
            insert blSalesHistories;
        }
        return blSalesHistories;
    }
}