B&L QA/objects/Account_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <description>IndiaSU field to collect subdivision of geographic region of the account located</description>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Ambala</fullName>
                </value>
                <value>
                    <fullName>Amritsar</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Chandigarh</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Trichy</fullName>
                </value>
                <value>
                    <fullName>Cochin</fullName>
                </value>
                <value>
                    <fullName>Coimbatore</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Indore</fullName>
                </value>
                <value>
                    <fullName>Jaipur</fullName>
                </value>
                <value>
                    <fullName>Jallandhar, Ludhiana</fullName>
                </value>
                <value>
                    <fullName>Kolkata</fullName>
                </value>
                <value>
                    <fullName>Lucknow</fullName>
                </value>
                <value>
                    <fullName>Mumbai</fullName>
                </value>
                <value>
                    <fullName>Mumbai -West</fullName>
                </value>
                <value>
                    <fullName>Pune</fullName>
                </value>
                <value>
                    <fullName>Rajkot</fullName>
                </value>
                <value>
                    <fullName>Surat</fullName>
                </value>
                <value>
                    <fullName>Vadodra</fullName>
                </value>
                <value>
                    <fullName>Hooghly</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>North1</fullName>
                </value>
                <value>
                    <fullName>North2</fullName>
                </value>
                <value>
                    <fullName>강남구</fullName>
                </value>
                <value>
                    <fullName>강동구</fullName>
                </value>
                <value>
                    <fullName>강북구</fullName>
                </value>
                <value>
                    <fullName>강서구</fullName>
                </value>
                <value>
                    <fullName>관악구</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DASRX_ABC_Classification__c</fullName>
        <description>DASRX ABC Classification from Peoplesoft</description>
        <label>ABC Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>Z</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maximum_days_from_last_visit__c</fullName>
        <description>Created for KOREA SOLTA.</description>
        <label>Maximum days from last visit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Visits_Per_Month__c</fullName>
        <description>Create For KOREA SOLTA.</description>
        <label>No Of Visits Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP{0000000000}</displayFormat>
        <label>Account Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Call_Plan__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Call Plan</label>
    <nameField>
        <displayFormat>CLP{00000000}</displayFormat>
        <label>Call Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Call_Plan_Detail__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan Details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for KOR SOLTA.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Plan__c</fullName>
        <description>INDSU field to capture the contact the planned visit is for.</description>
        <label>Call Plan</label>
        <referenceTo>Call_Plan__c</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>INDSU field to capture the date of the planned visit.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Call Plan Detail</label>
    <nameField>
        <displayFormat>CPD{00000000}</displayFormat>
        <label>Call Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plan Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/Test_CtrlCallPlanning_KOR_SOLTA.cls
/*
* 
* This class covers class CtrlCallPlanning_ChinaVC
* Author                        |Author-Email                                      |Date        |Comment
* ------------------------------|------------------------------------------------- |------------|----------------------------------------------------
* Venkateswara Reddy.C          |venkateswara.reddy2@bausch.com                    |11.15.2015  |First Draft
* 
* 
*/ 

@istest
private class Test_CtrlCallPlanning_KOR_SOLTA
{
      public static Boolean blnisManager;
    static TestMethod void TestMethod_CtrlCallPlanning_KoreaSu_1()
    {
      // User objTestUser = [SELECT Id, Name, Profile.Name,ManagerId,isActive,UserRole.Name  FROM User WHERE isActive = : true AND Profile.Name like : (Label.KOR_SOLTA_Label+'%') and ManagerId != : NULL AND UserRole.Name like : (Label.KOR_SOLTA_Label+ '%') AND UserRole.Name like : ('%' + 'KOR' + '%') LIMIT 1];
      
      User objTestUser = [Select id from User where Id = :UserInfo.getUserId()];
      
       system.runAs(objTestUser)
        {
            CtrlCallPlanning_KOR_SOLTA testCallPlanningObj = new CtrlCallPlanning_KOR_SOLTA();
            CtrlCallPlanning_KOR_SOLTA.CallPlan testCallPlanObj = new CtrlCallPlanning_KOR_SOLTA.CallPlan();
            CtrlCallPlanning_KOR_SOLTA.CallPlanDetail testCallPlanDetailObj = new CtrlCallPlanning_KOR_SOLTA.CallPlanDetail();
            CtrlCallPlanning_KOR_SOLTA.days testDays = new CtrlCallPlanning_KOR_SOLTA.days();
        }
        
        Account objTestAcc1 = new Account();
        system.runAs(objTestUser)
        {
            objTestAcc1 = new Account();
            objTestAcc1.name = 'Test Account1';
            objTestAcc1.OwnerId = objTestUser.Id;
            insert objTestAcc1;
        }   
        Account_Profile__c objTestAccProf1 = new Account_Profile__c();
        objTestAccProf1.DASRX_ABC_Classification__c = 'A';
        objTestAccProf1.Account__c = objTestAcc1.Id;
        objTestAccProf1.No_Of_Visits_Per_Month__c = 5;
        objTestAccProf1.Maximum_days_from_last_visit__c = 3;
        insert objTestAccProf1;
        
         
        system.runAs(objTestUser)
        {   
            //Single call plan and its detail object
            Call_Plan__c objTestCallPlan1 = new Call_Plan__c(); 
            objTestCallPlan1.Start_Date__c = Date.Today()-15;
            objTestCallPlan1.End_Date__c = Date.Today()-8;          
            objTestCallPlan1.OwnerId = userInfo.getUserId();        
            insert objTestCallPlan1; 
                   
           
            
            Call_Plan_Detail__c objTestCPD1 = new Call_Plan_Detail__c();        
            objTestCPD1.Call_Plan__c = objTestCallPlan1.Id;
             objTestCPD1.Date__c = Date.Today()-9;
            //objTestCPD1.Date__c = Date.Today().addDays(6);
            objTestCPD1.Account__c = objTestAcc1.Id;
            
            
            
            
          
         
            PageReference objPageRef = new PageReference('/apex/CallPlan_KOR_SOLTA?id=' + objTestCallPlan1.Id);
            Test.setCurrentPage(objPageRef);
            
            CtrlCallPlanning_KOR_SOLTA testCallPlanningObj1 = new CtrlCallPlanning_KOR_SOLTA();
            testCallPlanningObj1.cancel();
            //testCallPlanningObj1.doCloneAFterChoosingMonth();
            
            //ClsSingleMultiUtility.blnIsUpdateFromApproveReject = true;
            
            testCallPlanningObj1.blnisSaveFlag = true;
            testCallPlanningObj1.save();
            testCallPlanningObj1.getMonthsSelected();
            
            testCallPlanningObj1.blnisSubmitFlag = true;
            testCallPlanningObj1.save();
            
            testCallPlanningObj1.blnisApproveFlag = true;
            testCallPlanningObj1.save();
            
            testCallPlanningObj1.blnisRejectFlag = true;
            testCallPlanningObj1.save();
            
            
            //added by cvsr
             testCallPlanningObj1.getClass = 'A';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'B';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'C';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'D';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
          
            
            testCallPlanningObj1.getClass = '';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.clearAll();
            
                           
     
            
            
        }
        
    }  

    static TestMethod void TestMethod_CtrlCallPlanning_KoreaSu_2()
    {
        //User objTestUser = [SELECT Id, Name, Profile.Name,ManagerId,isActive,UserRole.Name   FROM User WHERE isActive = : true AND Profile.Name like : (Label.KOR_SOLTA_Label+'%') and ManagerId != : NULL AND UserRole.Name like : (Label.KOR_SOLTA_Label+ '%') AND UserRole.Name like : ('%' + 'KOR' + '%') LIMIT 1];
        
        User objTestUser = [Select id from User where Id = :UserInfo.getUserId()];
        
        
        
        
        system.runAs(objTestUser)
        {
            CtrlCallPlanning_KOR_SOLTA testCallPlanningObj = new CtrlCallPlanning_KOR_SOLTA();
            CtrlCallPlanning_KOR_SOLTA.CallPlan testCallPlanObj = new CtrlCallPlanning_KOR_SOLTA.CallPlan();
            CtrlCallPlanning_KOR_SOLTA.CallPlanDetail testCallPlanDetailObj = new CtrlCallPlanning_KOR_SOLTA.CallPlanDetail();
            CtrlCallPlanning_KOR_SOLTA.days testDays = new CtrlCallPlanning_KOR_SOLTA.days();
        }
        
        Account objTestAcc1 = new Account();
        system.runAs(objTestUser)
        {
            objTestAcc1 = new Account();
            objTestAcc1.name = 'Test Account1';
            objTestAcc1.OwnerId = objTestUser.Id;
            insert objTestAcc1;
        }   
        Account_Profile__c objTestAccProf1 = new Account_Profile__c();
        objTestAccProf1.DASRX_ABC_Classification__c = 'A';
        objTestAccProf1.Account__c = objTestAcc1.Id;
        objTestAccProf1.No_Of_Visits_Per_Month__c = 5;
        objTestAccProf1.Maximum_days_from_last_visit__c = 3;
        insert objTestAccProf1;
        
        
       
        system.runAs(objTestUser)
        {   
            //Single call plan and its detail object
            Call_Plan__c objTestCallPlan1 = new Call_Plan__c();  
            objTestCallPlan1.Start_Date__c=  Date.Today()-15;
            objTestCallPlan1.End_Date__c= Date.Today()-8;         
            objTestCallPlan1.OwnerId = userInfo.getUserId();        
            insert objTestCallPlan1;
    
            PageReference objPageRef = new PageReference('/apex/CallPlan_KOR_SOLTA?id=' + objTestCallPlan1.Id);
            Test.setCurrentPage(objPageRef);
            
            CtrlCallPlanning_KOR_SOLTA testCallPlanningObj1 = new CtrlCallPlanning_KOR_SOLTA();
            testCallPlanningObj1.cancel();
            
            ClsSingleMultiUtility.blnIsUpdateFromApproveReject = true;
            testCallPlanningObj1.doCloneAFterChoosingMonth();
            
            testCallPlanningObj1.blnisSaveFlag = true;
            testCallPlanningObj1.save();
            testCallPlanningObj1.getMonthsSelected();
            
            testCallPlanningObj1.blnisSubmitFlag = true;
            testCallPlanningObj1.save();
            
            testCallPlanningObj1.blnisApproveFlag = true;
            testCallPlanningObj1.save();
            
            testCallPlanningObj1.blnisRejectFlag = true;
            testCallPlanningObj1.save();
            
             testCallPlanningObj1.getClass = 'A';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'B';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'C';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'D';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            
          
            
            testCallPlanningObj1.getClass = '';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.clearAll();
        }
        
    } 
        //Implementing the N & Z classification customers in call plan Only for Korea. 
       
       
        static TestMethod void TestMethod_CtrlCallPlanning_Korea_3()
    {
      
  //User objKorUser = [SELECT Id, Name, Profile.Name,ManagerId,isActive,UserRole.Name FROM User WHERE isActive = : true AND Profile.Name like : (Label.KOR_SOLTA_Label+'%') and ManagerId != : NULL AND UserRole.Name like : (Label.KOR_SOLTA_Label+ '%') AND UserRole.Name like : ('%' + 'KOR' + '%') LIMIT 1];     
    User objKorUser  = [Select id from User where Id = :UserInfo.getUserId()];
        
        
        
        
        
        system.runAs(objKorUser)
        {
            CtrlCallPlanning_KOR_SOLTA testCallPlanningObj = new CtrlCallPlanning_KOR_SOLTA();
            CtrlCallPlanning_KOR_SOLTA.CallPlan testCallPlanObj = new CtrlCallPlanning_KOR_SOLTA.CallPlan();
            CtrlCallPlanning_KOR_SOLTA.CallPlanDetail testCallPlanDetailObj = new CtrlCallPlanning_KOR_SOLTA.CallPlanDetail();
            CtrlCallPlanning_KOR_SOLTA.days testDays = new CtrlCallPlanning_KOR_SOLTA.days();
           
        }
        
        Account objTestAcc3 = new Account();
        system.runAs(objKorUser)
        {
            objTestAcc3 = new Account();
            objTestAcc3.name = 'Test Account3';
            objTestAcc3.OwnerId = objKorUser.Id;
            insert objTestAcc3;
        }   
        Account_Profile__c objTestAccProf3 = new Account_Profile__c();
        objTestAccProf3.DASRX_ABC_Classification__c = 'N';
        objTestAccProf3.Account__c = objTestAcc3.Id;
        objTestAccProf3.No_Of_Visits_Per_Month__c = 5;
        objTestAccProf3.Area__c = 'Area';
        objTestAccProf3.Maximum_days_from_last_visit__c = 3;
        insert objTestAccProf3;
        
          
        system.runAs(objKorUser)
        {   
            //Single call plan and its detail object
            Call_Plan__c objTestCallPlan1 = new Call_Plan__c(); 
           
                   
            objTestCallPlan1.Start_Date__c = Date.Today().addDays(25);
            objTestCallPlan1.End_Date__c = Date.Today().addDays(31);        
            objTestCallPlan1.OwnerId = userInfo.getUserId();        
            insert objTestCallPlan1; 
            
            
            Call_Plan_Detail__c objTestCPD1 = new Call_Plan_Detail__c();        
            objTestCPD1.Call_Plan__c = objTestCallPlan1.Id;
           // objTestCPD1.Date__c = Date.Today()-9;
            objTestCPD1.Date__c = Date.Today().addDays(25);
            objTestCPD1.Account__c = objTestAcc3.Id;
            insert objTestCPD1;  
           
           
            
            PageReference objPageRef = new PageReference('/apex/CallPlan_KOR_SOLTA?id=' + objTestCallPlan1.Id);
            Test.setCurrentPage(objPageRef);
            
            CtrlCallPlanning_KOR_SOLTA testCallPlanningObj1 = new CtrlCallPlanning_KOR_SOLTA();
            testCallPlanningObj1.cancel();
            
            ClsSingleMultiUtility.blnIsUpdateFromApproveReject = true;
           //testCallPlanningObj1.doCloneAFterChoosingMonth();
            
            testCallPlanningObj1.blnisSaveFlag = true;
           testCallPlanningObj1.save();
            testCallPlanningObj1.getMonthsSelected();
            
            testCallPlanningObj1.blnisSubmitFlag = true;
            testCallPlanningObj1.save();
            
            testCallPlanningObj1.blnisApproveFlag = true;
            testCallPlanningObj1.save();
            
            testCallPlanningObj1.blnisRejectFlag = true;
            testCallPlanningObj1.save();
            
            List<SelectOption> list_options = testCallPlanningObj1.getArea();
            List<SelectOption> list_Classifictn = testCallPlanningObj1.getClassifictn();
            testCallPlanningObj1.getClass = 'A';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'B';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'C';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.getClass = 'D';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            
           
            
            testCallPlanningObj1.getClass = '';
            testCallPlanningObj1.getarea= 'Area';
            testCallPlanningObj1.go();
            testCallPlanningObj1.clearAll();
            
        }
        
    } 
    
     
     }