B&L QA/objects/Account_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP{0000000000}</displayFormat>
        <label>Account Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>INDSU formula field to collect account id to get account profile.</description>
        <formula>Physician__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INDSU Field for getting account profile related data.</description>
        <label>Account Profile</label>
        <referenceTo>Account_Profile__c</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>IndiaSU field to collect date on which the activity has occurred</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The hospital of the physician.</description>
        <label>Hospital</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IndiaSU field to collect physician from activity</description>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <description>CHNSU field to capture the session of the physician visit</description>
        <label>Session</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>APAC SU field to identify the physician visit status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/classes/Test_PhysicianVisit_BIU_UpdatePhysician.cls
@isTest(seealldata=true)
private class Test_PhysicianVisit_BIU_UpdatePhysician {

 public static testMethod void PhysicianVisit_BIU_Update(){
     test.startTest();
     account a=new account(name='Test_account',phone='123456');
     insert a;
     contact c=new contact(lastname='test_contact',accountid=a.id);
     insert c;
 
    
     Physician_Visit__c phy=new Physician_Visit__c();
    // phy.Account_ID__c=account_id;
     phy.Activity_Date__c=system.today();
     phy.Hospital__c=a.id;
     phy.Status__c='complete';
     phy.Session__c='AM'; 
     phy.Physician__c=c.id;
    
    // phy.Account_Profile__c=[select id from account_profile__c where account__c=:account_id].id;
     insert phy;
    // phy.Account_Profile__c=[select id from account_profile__c where account__c=:account_id].id;
    
    phy.Status__c='open';
     update phy;
     test.stopTest();
  
 }

}