B&L QA/objects/ASR_Sales__c.object
<CustomObject>
    <description>ASR sales data for SU</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated Account. Populated by a trigger.
Used by EMEA SU.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ASR Sales</relationshipLabel>
        <relationshipName>ASR_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_System_Id__c</fullName>
        <description>[SETID]-[Ship-to-Id] Used by EMEA SU.</description>
        <label>Legacy System Id</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Level_Id__c</fullName>
        <description>Used by EMEA SU.</description>
        <label>Product Level Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>[YYYY] Used by EMEA SU.</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>ASR Sales</label>
    <nameField>
        <displayFormat>SU-SD{0000000000}</displayFormat>
        <label>ASR Sales Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/TrgASRSales_BIU_setAccountID.cls
/*
* 
*   Test class for trigger "ASRSales_BIU_setAccountID"
* 
*    Author         |Author-Email                   |Date       |Comment
*    ---------------|-------------------------------|-----------|--------------------------------------------------
*    S Cardinali    |samantha.cardinali@bausch.com  |11.03.2010 |First draft
*
*/

@isTest
private class TrgASRSales_BIU_setAccountID{
  static testMethod void testASRSales_BIU_setAccountID() {

      //Insert Account
      RecordType rtShipTo = [SELECT Id From RecordType Where Name = 'Ship To Account' Limit 1];
      Account testAccount = new Account (
        Name = 'SCTEST123',
        RecordType = rtShipTo,
        Legacy_System_ID__c = 'UNKGD00123456'
      );
      try{
        insert testAccount;
      } catch(Exception e) {
        System.debug('Error adding Account: ' + e.getMessage());
      }

      //Insert ASR Sales Record
      ASR_Sales__c testSales = new ASR_Sales__c (
        Year__c = '2010',
        Product_Level_Id__c = 'ABC12345',
        Legacy_System_ID__c = 'UNKGD00123456'
      );
      try{
        insert testSales;
      } catch(Exception e) {
        System.debug('Error adding testSales: ' + e.getMessage());
      }

      //Check AccountID populated correctly
      ASR_Sales__c sInsertedSales = [Select Id, Account__c From ASR_Sales__c Where Id = :testSales.Id];
      System.assertEquals(testAccount.Id, sInsertedSales.Account__c);
    
   }
}