B&L QA/objects/Call_Plan__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>INDSU field to capture the status of the plan.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Plan</label>
    <nameField>
        <displayFormat>CLP{00000000}</displayFormat>
        <label>Call Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Call_Plan_Detail__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan Details</description>
    <fields>
        <fullName>Call_Plan__c</fullName>
        <description>INDSU field to capture the contact the planned visit is for.</description>
        <label>Call Plan</label>
        <referenceTo>Call_Plan__c</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Call__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INDSU field to indicate if a visits is planned or not.</description>
        <label>Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>INDSU field to capture the date of the planned visit.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Physician_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INDSU field to capture the contact the planned visit is for.</description>
        <label>Physician Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Plan Detail</label>
    <nameField>
        <displayFormat>CPD{00000000}</displayFormat>
        <label>Call Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plan Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>IndiaSU field to collect date on which the activity has occurred</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Physician_Name__c</fullName>
        <formula>Physician__r.FirstName+ Physician__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Physician Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IndiaSU field to collect physician from activity</description>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>APAC SU field to identify the physician visit status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/classes/CtrlCallPlanErrors.cls
/**
* 
* This is the controller for reporting the errors on the call plan 
* Author               |Author-Email                       |Date        |Comment
* ---------------------|---------------------------------- |------------|----------------------------------------------------
* Yash Agarwal         |yash.agarwal@listertechnologies.com|20.05.2010  |First Draft for CtrlCallPlanning_planDetail page
* Sourav Mitra         |sourav.mitra@listertechnologies.com|08.09.2010  |Changes to incorporate China SU
*/
public class CtrlCallPlanErrors
{
    public id idContact ;
    public Date datLastMonthEndDate;
    public Date datLastMonthStartDate;
    
    //public Id idRecordTypeCallPlanDetail;
    //public Id idRecordTypePhysicianVisit;
    public List<RecordType> list_CallPlanRecordTypes;
    public List<RecordType> list_PhysicianVisitRecordTypes;
    
    public Map<Date,Physician_Visit__c> map_ActivityDate_PhysicianVisit ;
    public List<CallPlanError> list_CallPlanError{ get; set;}
    public List<Call_Plan_Detail__c> list_callPlanDetailRecords = new List<Call_Plan_Detail__c>();
    public List<Physician_Visit__c> list_physicianVist= new List<Physician_Visit__c>();
    public class CallPlanError{
    
        public Call_Plan_Detail__c objCallPlanDetail{ get; set;}
        public String strActual { get; set;}
        public CallPlanError(){
        
            objCallPlanDetail = new Call_Plan_Detail__c();
            strActual = '';
        }
    }
    
    CallPlanError cpe = new CallPlanError();
    
    public CtrlCallPlanErrors()
    {
        String strStartDate;
        String strEndDate;
        
        //getting the record type ids
        list_CallPlanRecordTypes = [SELECT Id FROM RecordType 
                                        WHERE Name IN ('INDSU Call Plan Detail','APACSU Call Plan Detail') AND SObjectType='Call_Plan_Detail__c'];
        
        list_PhysicianVisitRecordTypes = [SELECT Id FROM RecordType 
                                        WHERE Name IN ('INDSU Sales Planned','INDSU Sales Planned') AND SObjectType='Physician_Visit__c'];    
        
        
        if(ApexPages.currentPage().getParameters().get('conId') != null)
            idContact = ApexPages.currentPage().getParameters().get('conId');
            
        if(ApexPages.currentPage().getParameters().get('start') != null)
            strStartDate = ApexPages.currentPage().getParameters().get('start');
            
        if(ApexPages.currentPage().getParameters().get('end') != null)
            strEndDate = ApexPages.currentPage().getParameters().get('end');
            
        if(idContact != null)
        {
            if(strStartDate != null && strEndDate != null){
            
                datLastMonthStartDate = date.valueOf(strStartDate);
                system.debug('Start>>' + datLastMonthStartDate);
                datLastMonthEndDate = date.valueOf(strEndDate);
                system.debug('End>>' + datLastMonthEndDate );
                system.debug('End>>' + idContact );
                list_callPlanDetailRecords = [Select Id,
                
                                                    Physician_Name__c,
                                                     Physician_Name__r.Name,
                                                    Physician_Name__r.AccountId,
                                                    Physician_Name__r.Account.name,
                                                    Call_Plan__c,
                                                    Date__c,
                                                    Call__c From Call_Plan_Detail__c where Physician_Name__c =:idContact 
                                                                                    AND Date__c >=  :datLastMonthStartDate
                                                                                    AND Date__c <= :datLastMonthEndDate
                                                                                    AND RecordTypeId IN :list_CallPlanRecordTypes
                                                                                    AND Call__c = true];
                if(list_callPlanDetailRecords.size() > 0)
                {
                    list_physicianVist = [Select Id,
                                                Activity_Date__c,
                                                Physician__c,
                                                Status__c From Physician_Visit__c Where Physician__c = :idContact
                                                                                AND Activity_Date__c >=  :datLastMonthStartDate
                                                                                AND Activity_Date__c <= :datLastMonthEndDate
                                                                                AND RecordTypeId IN :list_PhysicianVisitRecordTypes
                                                                                AND Status__c = 'Completed'];
                                                                                
                    if(list_physicianVist.size() >0)
                    {
                        map_ActivityDate_PhysicianVisit = new Map<Date,Physician_Visit__c>();  for(Physician_Visit__c phyV : list_physicianVist){ map_ActivityDate_PhysicianVisit.put(phyV.Activity_Date__c,phyV);
                        }
                        list_CallPlanError = new List<CallPlanError>();  for(Call_Plan_Detail__c cpd :list_callPlanDetailRecords){ cpe = new callPlanError(); cpe.objCallPlanDetail= cpd;
                            if(map_ActivityDate_PhysicianVisit.containsKey(cpd.Date__c)){  cpe.strActual = 'Y';
                            } else{
                                cpe.strActual = 'N';
                            }
                            list_CallPlanError.add(cpe);
                        }
                        
                    } else{
                        addErrorMessage('No visits for the given contact was met in the previous month');
                    }
                } else{
                    addErrorMessage('No planned calls exist for the given contact');
                }
                                
            } else{
                addErrorMessage('Months start/end date not known');
            }
        } else{
            addErrorMessage('No physician Id specified');
        }
        
        
    }
    
    public void addErrorMessage(String error){
        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, error);
        ApexPages.addMessage(msg);
    }
}