B&L QA/objects/Call_Plan__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Executive_Comments__c</fullName>
        <description>INDSU field to capture the comments by the executive(Sales or Service)</description>
        <label>Executive Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manager_Comments__c</fullName>
        <description>INDSU field to capture the comments by the manager</description>
        <label>Manager Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>INDSU field to indicate the month the plan is for.</description>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INDSU field to capture the status of the plan.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>INDSU field to indicate the year the plan is for.</description>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Plan</label>
    <nameField>
        <displayFormat>CLP{00000000}</displayFormat>
        <label>Call Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Call_Plan_Detail__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan Details</description>
    <fields>
        <fullName>Call_Plan__c</fullName>
        <description>INDSU field to capture the contact the planned visit is for.</description>
        <label>Call Plan</label>
        <referenceTo>Call_Plan__c</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Plan Detail</label>
    <nameField>
        <displayFormat>CPD{00000000}</displayFormat>
        <label>Call Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plan Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Weekly_Call_Plan_Profiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting for KOREA SOLTA.</description>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Weekly Call Plan Profiles</label>
</CustomObject>

B&L QA/classes/ExtViewCallPlan_KOR_SOLTA.cls
/**
* 
*   This class is used as the extension for the page which overrides standard view page for Call Plan 
*   Redirects to standard layout for KOREA SOLTA users
*
*    Author                |Author-Email                                       |Date       |Comment
*    ----------------------|---------------------------------------------------|-----------|---------------------------------
*    Venkateswara Reddy    | venkateswara.reddy2@bausch.com                    |12.Nov.2015| First draft
* Test Class : Test_ExtViewCallPlan_KOR_SOLTA   
*/
public with sharing class ExtViewCallPlan_KOR_SOLTA {

    //Call plan
    public Call_Plan__c objCallPlan {get; set;}
    //Owner of the call
    public String strOwner {get; set;}
    //Has the status about the call plan details
    public Boolean blnHasDetails {get; set;}
    //Week which is selected
    public String strWeek{get;set;}
    
    //Call Id
    public String strCallId;
    public String retURL;
    //Is the call plan editable based on the status
    public Boolean blnIsEditable {get; set;}
        
    //Constructor
    public ExtViewCallPlan_KOR_SOLTA(ApexPages.StandardController controller){
        
        strCallId = Apexpages.currentPage().getParameters().get('Id');
        retURL =  Apexpages.currentPage().getParameters().get('retURL');
        blnHasDetails = false;
        blnIsEditable = true;
        
        if(strCallId!=NULL && strCallId!=''){
             
            Call_Plan__c[] list_CallPlans = [SELECT Id, 
                                                    Name, 
                                                    Status__c, 
                                                    Month__c, 
                                                    Year__c,
                                                    Owner.Name, 
                                                    OwnerId, 
                                                    Createddate,                                                    
                                                    Manager_Comments__c,
                                                    Executive_Comments__c,
                                                    Start_Date__c,
                                                    End_Date__c,
                                                    Week__c,
                                                    (SELECT Id FROM Call_Plan_Detail__r LIMIT 1)
                                                FROM Call_Plan__c  
                                                WHERE Id = :strCallId LIMIT 1];
                                                
            
            if(list_CallPlans.size() > 0){
                objCallPlan = list_CallPlans[0];
                
            if(objCallPlan.Call_Plan_Detail__r.size() > 0)
                blnHasDetails = true;
                    
            strOwner = list_CallPlans[0].Owner.Name;
          
            //Week format will be displayed based on the format available in the custom settings for each role
            if(objCallPlan.Start_Date__c!= null && objCallPlan.End_Date__c!= null)            
                strWeek = ClsSingleMultiUtility.getDisplayWeekInDifferentFormat(objCallPlan.Start_Date__c, objCallPlan.End_Date__c, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId())); //12.Jan.2011
                
            if(objCallPlan.Status__c == 'Submitted' || objCallPlan.Status__c == 'Approved')
                blnIsEditable = false;
                
            if(blnIsEditable){  
                    
                Profile thisProfile = [select Id,Name from Profile where Id =: userInfo.getProfileId() LIMIT 1];
        
                if(thisProfile !=NULL && thisProfile.Name.contains(Label.manager_label))
                    blnIsEditable = false;
                    
                if(objCallPlan.Status__c == 'Submitted')
                    blnIsEditable = false;
            }
                
            }
        } 
        
    }
    
    //Schedule the call plan
    public PageReference schedule()
    {
        PageReference pagRef;

        pagRef = new PageReference('/apex/CallPlan_KOR_SOLTA?id=' + objCallPlan.Id);
        return pagRef;
    }
    
    //Cancel the call plan
    public PageReference cancel()
    {
        String strRetURL = '/' + Call_Plan__c.SObjectType.getDescribe().getKeyPrefix() + '/o';
        return (new PageReference(strRetURL));
    }    
    
    //this section will decide about the call plan format(Week or Month) to be displayed
    public PageReference redirectFromNewPage()
    {        
        Boolean blnIsWeeklyPlan = false;
     

        UserRole objCurrentRole;
        
        //Taking the profile names for weekly call plan from the custom setting
        Map<String,Weekly_Call_Plan_Profiles__c> map_ProfileNameFromCustSetting = new Map<String,Weekly_Call_Plan_Profiles__c>();
        //Set<String> set_ProfileNames = new Set<String>();
        Map<String,Weekly_Call_Plan_Profiles__c> map_ProfileNames = new Map<String,Weekly_Call_Plan_Profiles__c>();
        
        map_ProfileNameFromCustSetting = Weekly_Call_Plan_Profiles__c.getAll();
        system.debug('map_ProfileNameFromCustSetting>>>'+map_ProfileNameFromCustSetting);
        
        for(Weekly_Call_Plan_Profiles__c objTemp : map_ProfileNameFromCustSetting.values())
        {
            //set_ProfileNames.add(objTemp.Profile_Name__c);
            map_ProfileNames.put(objTemp.Profile_Name__c, objTemp);
        }
        //system.debug('set_ProfileNames>>'+set_ProfileNames);
        
        if(UserInfo.getUserRoleId() == null)
            blnIsWeeklyPlan = false; 
        else
            //Profile objCurrentProfile = [SELECT Id, Name FROM Profile WHERE Id = : userInfo.getProfileId() LIMIT 1];
            objCurrentRole = [SELECT Id, Name FROM UserRole WHERE Id =: UserInfo.getUserRoleId() LIMIT 1];
        
        if(objCurrentRole != null)
        {
            //for(String strTempProfName : set_ProfileNames)
            Set<String> set_ProfileNames = map_ProfileNames.keySet();
            for(String key : set_ProfileNames)
            {
                Weekly_Call_Plan_Profiles__c objWkCpProfs = map_ProfileNames.get(key);

                if(objCurrentRole.Name != null && objCurrentRole.Name.startsWith(objWkCpProfs.Profile_Name__c) && (objWkCpProfs.Region__c == 'Korea'))
                    blnIsWeeklyPlan = true;                                  

                
            }
        }
        
       
        if(!blnIsWeeklyPlan)        {
            String strObjCode = Call_Plan__c.SObjectType.getDescribe().getKeyPrefix();
            if(retURL!=NULL && retURL!='')
                return (new PageReference('/' + strCallId + '?nooverride=1' + '&retURL=' + retURL));
            return (new PageReference('/' + strCallId + '?nooverride=1'));
        }
        return null;
    }
   
}