B&L QA/objects/Call_Plan__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>INDSU field to indicate the month the plan is for.</description>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INDSU field to capture the status of the plan.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>INDSU field to indicate the year the plan is for.</description>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Plan</label>
    <nameField>
        <displayFormat>CLP{00000000}</displayFormat>
        <label>Call Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Call_Plan_Detail__c.object
<CustomObject>
    <description>INDSU Sales/Service team members to upload the monthly call plan Details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for KOR SOLTA.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Plan__c</fullName>
        <description>INDSU field to capture the contact the planned visit is for.</description>
        <label>Call Plan</label>
        <referenceTo>Call_Plan__c</referenceTo>
        <relationshipLabel>Call Plan Detail</relationshipLabel>
        <relationshipName>Call_Plan_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>INDSU field to capture the date of the planned visit.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Call Plan Detail</label>
    <nameField>
        <displayFormat>CPD{00000000}</displayFormat>
        <label>Call Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plan Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>APAC SU field to identify the physician visit status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/classes/Test_ExtCreateCallPlan_KOR_SOLTA.cls
@isTest(SeeAllData=true)
private class Test_ExtCreateCallPlan_KOR_SOLTA
 {
    static TestMethod void TestMethod_clsSingleMultiUtil(){
    
      UserRole objRoleSalesAdmin = [Select Id From UserRole where name LIKE '%KOR SOLTA%' LIMIT 1]; 
        Profile objProfileIntegrationUser = [SELECT Id FROM profile WHERE name LIKE '%KOR SOLTA%' LIMIT 1]; 
        User objUserIngetration = new User(alias = 'integra', email='integration@testorg.com', emailencodingkey='UTF-8',
                             lastname='Testing', languagelocalekey='en_US', localesidkey='en_US', timezonesidkey='America/Los_Angeles',
                             username='integration123@testorg.com', profileid = objProfileIntegrationUser.Id, UserroleId = objRoleSalesAdmin.Id);
        Database.SaveResult sr = Database.insert(objUserIngetration);
        User objTestUser = [SELECT ID FROM USER WHERE ID = :sr.getId()];
        
        Account objTestAcc = new Account();
        
         system.runAs(objTestUser)
        {
                      Test.startTest();
        ClsSingleMultiUtility.WeekDetails objTestContactDetails = new ClsSingleMultiUtility.WeekDetails();                
        ClsSingleMultiUtility.getParents(UserInfo.getUserRoleId());
        
        DateTime dtTimeTest1 = DateTime.newInstance(Date.Today().year(),Date.Today().month(),Date.Today().day()-1);
        DateTime dtTimeTest2 = DateTime.newInstance(Date.Today().year(),Date.Today().month(),Date.Today().day()-2);
        DateTime dtTimeTest3 = DateTime.newInstance(Date.Today().year(),Date.Today().month(),Date.Today().day()-3);
        DateTime dtTimeTest4 = DateTime.newInstance(Date.Today().year(),Date.Today().month(),Date.Today().day()-4);
        DateTime dtTimeTest5 = DateTime.newInstance(Date.Today().year(),Date.Today().month(),Date.Today().day()-5);
        DateTime dtTimeTest6 = DateTime.newInstance(Date.Today().year(),Date.Today().month(),Date.Today().day()-6);
        
        
        ClsSingleMultiUtility.getWeekInDifferentFormat(Datetime.now(),ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        ClsSingleMultiUtility.getWeekInDifferentFormat(dtTimeTest1, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        ClsSingleMultiUtility.getWeekInDifferentFormat(dtTimeTest2, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        ClsSingleMultiUtility.getWeekInDifferentFormat(dtTimeTest3, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        ClsSingleMultiUtility.getWeekInDifferentFormat(dtTimeTest4, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        ClsSingleMultiUtility.getWeekInDifferentFormat(dtTimeTest5, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        ClsSingleMultiUtility.getWeekInDifferentFormat(dtTimeTest6, ClsSingleMultiUtility.getWeekFormat(UserInfo.getUserRoleId()));
        
        ClsSingleMultiUtility.getDisplayWeek(Date.Today()-7,Date.Today());
        ClsSingleMultiUtility.getDisplayDate(Date.Today());
        ClsSingleMultiUtility.getListOfDays(Date.Today()-7,Date.Today());  
        ClsSingleMultiUtility.getWeekStringAndWeekDateMap();          
          
            objTestAcc.name = 'Test Account';
            objTestAcc.OwnerId = objTestUser.Id;
            insert objTestAcc; 
            
            //Single call plan and its detail object
            Call_Plan__c objTestCallPlan = new Call_Plan__c();        
            objTestCallPlan.Start_Date__c = Date.Today().toStartOfMonth().addDays(-50);
            objTestCallPlan.End_Date__c = Date.Today().toStartOfMonth();   
            objTestCallPlan.Month__c = 'Nov';   
            objTestCallPlan.Year__c = String.valueOf(Date.today().year());              
            objTestCallPlan.OwnerId = userInfo.getUserId();        
            insert objTestCallPlan; 
                
        
        Call_Plan_Detail__c objTestCPD = new Call_Plan_Detail__c();        
            objTestCPD.Call_Plan__c = objTestCallPlan.Id;
            objTestCPD.Date__c = Date.Today().toStartOfMonth().addDays(-48);
            objTestCPD.Account__c = objTestAcc.Id;
            insert objTestCPD;  
         
      Test.stopTest();      
    
   }
    }//method
    static TestMethod void TestMethod_ExtCreateCallPlan()
    {       
       
        UserRole objRoleSalesAdmin = [Select Id From UserRole where name LIKE '%KOR SOLTA%' LIMIT 1]; 
        Profile objProfileIntegrationUser = [SELECT Id FROM profile WHERE name LIKE 'KOR SOLTA Sales Rep' LIMIT 1];  
          
        User objUserIngetration = new User(alias = 'integra', email='integration@testorg.com', emailencodingkey='UTF-8',
                             lastname='Testing', languagelocalekey='en_US', localesidkey='en_US', timezonesidkey='America/Los_Angeles',
                             username='integration123@testorg.com', profileid = objProfileIntegrationUser.Id, UserroleId = objRoleSalesAdmin.Id);
        Database.SaveResult sr = Database.insert(objUserIngetration);
        User objTestUser = [SELECT ID FROM USER WHERE ID = :sr.getId()];
        
        Account objTestAcc = new Account();
        
   RecordType rt =  [SELECT Id, Name FROM RecordType WHERE SObjectType='Physician_Visit__c' and Name = 'KORSOLTA Sales Planned' limit 1];                                 
                                               
        system.runAs(objTestUser)
        {
               Test.startTest();
            objTestAcc.name = 'Test Account';
            objTestAcc.OwnerId = objTestUser.Id;
            insert objTestAcc;
            
            //Single call plan and its detail object
            Call_Plan__c objTestCallPlan = new Call_Plan__c();        
            objTestCallPlan.Start_Date__c = Date.Today().toStartOfMonth().addDays(-50);
            objTestCallPlan.End_Date__c = Date.Today().toStartOfMonth();   
            objTestCallPlan.Month__c = 'Nov';   
            objTestCallPlan.Year__c = String.valueOf(Date.today().year());         //'2011';       
            objTestCallPlan.OwnerId = userInfo.getUserId();        
            insert objTestCallPlan;
            
            Call_Plan_Detail__c objTestCPD = new Call_Plan_Detail__c();        
            objTestCPD.Call_Plan__c = objTestCallPlan.Id;
            objTestCPD.Date__c = Date.Today().toStartOfMonth().addDays(-48);
            objTestCPD.Account__c = objTestAcc.Id;
            insert objTestCPD; 
        
           objTestCallPlan.status__c = 'Approved';
          // update objTestCallPlan;
         Test.stopTest();  
        
        }
        
        Account objTestAcc1 = new Account();
        
            
        system.runAs(objTestUser)
        {
           
            objTestAcc1.name = 'Test Account1';
            objTestAcc1.OwnerId = objTestUser.Id;
            insert objTestAcc1;
 
             
            //Single call plan and its detail object
            Call_Plan__c objTestCallPlan1 = new Call_Plan__c();        
            objTestCallPlan1.start_Date__c = Date.Today()-7;
            objTestCallPlan1.End_Date__c = Date.Today();        
            objTestCallPlan1.OwnerId = userInfo.getUserId();   
            objTestCallPlan1.Year__c = String.valueOf(Date.today().year());            
            insert objTestCallPlan1;
        
        
            Call_Plan_Detail__c objTestCPD1 = new Call_Plan_Detail__c();        
            objTestCPD1.Call_Plan__c = objTestCallPlan1.Id;
            objTestCPD1.Date__c = Date.Today();
            objTestCPD1.Account__c = objTestAcc1.Id;
            //insert objTestCPD1;        
        
  //getting data from Data base
  Call_Plan__c  objTestCallPlan2 = [select id,name,start_Date__C,End_Date__C,status__c,Year__c ,OwnerId  from Call_Plan__c where status__c = 'Draft' limit 1];
  
     
        
            ApexPages.StandardController testController = new ApexPages.StandardController(objTestCallPlan2);  
            ExtCreateCallPlan_KOR_SOLTA objTestExtCreateCallPlan = new ExtCreateCallPlan_KOR_SOLTA(testController);
            
            PageReference objPageRef = new PageReference('/apex/ExtCreateCallPlan_SingleWeek_KOR_SOLTA?Id=' + objTestCallPlan2.Id);
            Test.setCurrentPage(objPageRef);
            
           
            objTestExtCreateCallPlan.saveAndSchedule();
            objTestExtCreateCallPlan.schedule();
            objTestExtCreateCallPlan.getAllWeeks();
            objTestExtCreateCallPlan.save();
            objTestExtCreateCallPlan.saveCallPlan();        
            objTestExtCreateCallPlan.cancel();        
            
            testController = new ApexPages.StandardController(objTestCallPlan2);  
            objTestExtCreateCallPlan = new ExtCreateCallPlan_KOR_SOLTA(testController);
            
            objPageRef = new PageReference('/apex/ExtCreateCallPlan_SingleWeek_KOR_SOLTA?Id=' + objTestCallPlan2.Id);
            Test.setCurrentPage(objPageRef);
            
            objTestExtCreateCallPlan.saveAndSchedule();
            objTestExtCreateCallPlan.schedule();
            objTestExtCreateCallPlan.getAllWeeks();
            objTestExtCreateCallPlan.save();//
            objTestExtCreateCallPlan.saveCallPlan(); //       
            objTestExtCreateCallPlan.cancel();        
            objTestExtCreateCallPlan.redirectFromNewPage();
            
            //testController = new ApexPages.StandardController(objTestCallPlan2);  
            //objTestExtCreateCallPlan = new ExtCreateCallPlan_KOR_SOLTA(testController);
            
            //objPageRef = new PageReference('/apex/ExtCreateCallPlan_SingleWeek?RecordType='+list_RTMultiple[0].Id);
            //Test.setCurrentPage(objPageRef);
            
        }
    }
}