B&L QA/objects/Carrier__c.object
<CustomObject>
    <description>NORDCSS: Used in the Nordic CSS project to store information relating to carriers and the link to the carrier tracking website</description>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Carrier</label>
    <nameField>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Shipping_History__c.object
<CustomObject>
    <description>NORDCSS: Stores the Shipping History from Peoplesoft relating to Orders.</description>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <referenceTo>Carrier__c</referenceTo>
        <relationshipLabel>Shipping History</relationshipLabel>
        <relationshipName>Shipping_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tracking_No__c</fullName>
        <description>No. provided by the carrier - will be used with the carrier&apos;s website where possible.</description>
        <label>Tracking No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Shipping History</label>
    <nameField>
        <displayFormat>SH-{YY}{0000000}</displayFormat>
        <label>Shipping History Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B&L QA/classes/ClsTreeShipment.cls
/**
* 
* 	This class holds a structure as a helping construct for displaying Shipment information related to  
*	Order Line Item information in a tree structure for Order Tracking. 
*
*  	Author		     |Author-Email			   	     	|Date		|Comment
*  	-----------------|----------------------------------|-----------|--------------------------------------------------
*  	Dennis Flüchter  |dennis.fluechter@itbconsult.com 	|09.09.2009 |First draft
*
*
*/

public with sharing class ClsTreeShipment {
	
	/*************************************************************************
  	* Define Varibales and Properties
  	*************************************************************************/
  	
  	public Shipping_History__c shipment {get; set;}
  	public List<ClsTreeItem> list_items {get; set;}
  	
  	/*************************************************************************
  	* Constructor
  	*************************************************************************/
  	
  	public ClsTreeShipment(){
  		this.shipment = new Shipping_History__c();
  		this.list_items = new List<ClsTreeItem>();
  	}
  	
  	
  	/*************************************************************************
  	* All Methods Except Getter and Setter Methods
  	*************************************************************************/
  	
  	/*************************************************************************
  	* Getter and Setter Methods
  	*************************************************************************/
  	
  	public List<Shipping_History__c> getshipmentList(){
  		List<Shipping_History__c> list_return = new List<Shipping_History__c>();
  		list_return.add(this.shipment);
  		return list_return;
  	}
  	
  	public Boolean gethasMultipleItems(){
  		Boolean returnValue = false;
  		if (this.list_items.size() > 1){
  			returnValue = true;
  		}
  		return returnValue;
  	}
  	
  	public String gettrackingURL(){
  		System.debug('********** getTrackingURL **********');
  		String returnValue = ''; //'http://online.pannordic.com/pn_logistics/tracking/pub_shipment_details.jsp?shipmentId=' + this.shipment.Tracking_No__c;
  		if (this.shipment.Carrier__c != null){
  			returnValue = this.shipment.Carrier__r.Website__c + this.shipment.Tracking_No__c;
  		}
  		System.debug('--> returnValue: ' + returnValue);
  		return returnValue;	
  	}
  	
  	public Boolean getemptyTrackingWebsite(){
  		Boolean returnValue = false;
  		if (this.shipment.Carrier__c == null){
  			returnValue = true;
  		} else {
  			if(this.shipment.Carrier__r.Website__c == null){
  				returnValue = true;
  			}
  		}
  		return returnValue;
  	}
}