B&L QA/objects/Consignment_Search_Data__c.object
<CustomObject>
    <description>Custom object used to hold search results from users&apos; consignment searches.  This object holds the contents of each user&apos;s most current search, and after every search, the data found from the previous search gets deleted.</description>
    <fields>
        <fullName>Search_ID__c</fullName>
        <description>A unique ID generated by the consignment search Apex class that is passed to the integration.  It gives each search an identifier so that the call to delete previous searches can be made.</description>
        <label>Search ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <description>This is the standard SFDC ID from the User object for the user that performed the search.</description>
        <label>User ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Consignment Search Data</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Search Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consignment Search Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B&L QA/classes/deleteConsignmentData_Test.cls
/**     
    
    Developer       Email                       Date
    Vijay Singh     vijay.singh@aequor.com      28/03/2013
    
 */
@isTest
private class deleteConsignmentData_Test {

    static testMethod void deleteConsignmentData() {
        
            Consignment_Search_Data__c obj = new Consignment_Search_Data__c();
            obj.User_ID__c = UserInfo.getUserId();
            obj.Search_ID__c  = 'test search id';
            insert obj;
            
            Consignment_Search_Data__c obj1 = new Consignment_Search_Data__c();
            obj1.User_ID__c = UserInfo.getUserId();
            obj1.Search_ID__c  = 'different test search id';
            insert obj1;
    }
}