B&L QA/objects/Contact_Profile__c.object
<CustomObject>
    <description>To store profile questions related to Contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Profiles</relationshipLabel>
        <relationshipName>Contact_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <description>Field created for KORSOLTA Users.</description>
        <label>Speciality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Profile</label>
    <nameField>
        <displayFormat>CP{0000000000}</displayFormat>
        <label>Contact Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/ConProf_AIAU_SetSpecialityonContactTest.cls
@isTest
public class ConProf_AIAU_SetSpecialityonContactTest {
    Static testmethod void contactfieldupdate(){
       
        RecordType rec = [Select ID, Name from RecordType where Name = 'KOR SOLTA ContactProfile' AND SObjectType='Contact_Profile__c'];
        
        Contact c = new Contact(lastname='bajaj',Speciality__c='');
        insert c;
         
        Contact con = [select ID,Speciality__c from Contact where ID=:c.ID];
         
        Contact_Profile__c cp =new Contact_Profile__c(Speciality__c='DM',Contact__c=con.ID,RecordTypeID=rec.ID);
        insert cp;
        
        con.Speciality__c=cp.Speciality__c;
        update con;
        
        cp.Speciality__c='SM';
        update cp;
    }
}