B&L QA/objects/Crystalens_Premium_Partnership_Program__c.object
<CustomObject>
    <description>P3 Program in US Surgical for Crystalens</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Crystalens Premium Partnership Program</relationshipLabel>
        <relationshipName>Crystalens_Premium_Partnership_Program</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Crystalens Premium Partnership Program</label>
    <nameField>
        <displayFormat>CPPP-{00000000}</displayFormat>
        <label>Crystalens Premium Partnership Program N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crystalens Premium Partnership Program</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/Test_enforceSingle_Crystalens_PPP_record.cls
/*
* First Draft : Kuldeep Singh
* Modified By : 
* Test Class for Trigger :enforceSingle_Crystalens_PP_Program_record 
*
*/


@isTest
Private Class Test_enforceSingle_Crystalens_PPP_record
    {

    Static TestMethod void Test_enforceSingle_Crystalens_PPP_record()
        {
             
            Account acc =new Account(name='Test123');
            insert acc;
            
            Crystalens_Premium_Partnership_Program__c cppp=new Crystalens_Premium_Partnership_Program__c(Account__c=acc.id);
            insert cppp;
            
            //Crystalens_Premium_Partnership_Program__c cpp=new Crystalens_Premium_Partnership_Program__c(Account__c=acc.id);             
            //insert cpp;            
        }
    }