B&L QA/objects/Dashboard_Router__c.object
<CustomObject>
    <description>INDSU record type to maintain dashboard name and map url to drill down to multiple dashboards</description>
    <fields>
        <fullName>Chart_Name__c</fullName>
        <description>INDSU field to capture the chart name</description>
        <label>Chart Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Col_To_Point_To__c</fullName>
        <description>INDSU field to capture the column of the dashboard to point to</description>
        <label>Col To Point To</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dashboard_Id_To_Open__c</fullName>
        <description>INDSU field to capture the SF ID of the dashboard to open on clicking on the chart</description>
        <label>Dashboard Id To Open</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Row_To_Point_To__c</fullName>
        <description>INDSU field to capture the row of the dashboard to point to</description>
        <label>Row To Point To</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dashboard Router</label>
    <nameField>
        <displayFormat>DR-{0000000}</displayFormat>
        <label>Chart Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Router</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/CtrlDashboardRouter_Test.cls
@isTest
private class CtrlDashboardRouter_Test {

    static testMethod void myUnitTest() {
    	//To insert a record in dashboard router object.
    	Dashboard_Router__c objDashboardRouter = new Dashboard_Router__c();
    	objDashboardRouter.Chart_Name__c = 'Test_Chart_001';
    	objDashboardRouter.Dashboard_Id_To_Open__c = '111111111';
    	objDashboardRouter.Col_To_Point_To__c = 0;
    	objDashboardRouter.Row_To_Point_To__c = 0;
    	insert objDashboardRouter;
    	
    	//PageReference testPg = new PageReference();
		Test.setCurrentPage(new PageReference('/apex/DashboardRouter?chartName='+objDashboardRouter.Chart_Name__c));
		ctrlDashboardRouter obj = new ctrlDashboardRouter();
		obj.route();
		
		/*pr.getParameters().put('chartName', 'Test_Chart_001');
		try{
			Test.invokePage(pr);
		}catch(Exception ex){
			System.debug(ex);
		}*/
    }
}