B&L QA/objects/Joint_Field_Work__c.object
<CustomObject>
    <description>IndiaSU Object to hold feedback of joint field work done by manager and sales/service executive</description>
    <fields>
        <fullName>Physician_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Physician Visit</label>
        <referenceTo>Physician_Visit__c</referenceTo>
        <relationshipLabel>Joint Field Work</relationshipLabel>
        <relationshipName>Joint_Field_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Joint Field Work</label>
    <nameField>
        <label>Joint Field Work Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Field Work</pluralLabel>
    <recordTypes>
        <fullName>INDSU</fullName>
        <active>true</active>
        <description>India SU joint field work record type</description>
        <label>INDSU</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Monthly_Implantation_Detail__c.object
<CustomObject>
    <description>APACSU object used to capture and calculate market share for B&amp;L and Competitor Products.</description>
    <label>Monthly Implantation Detail</label>
    <nameField>
        <displayFormat>CP- {00000000}</displayFormat>
        <label>Monthly Implantation Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Implantation Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Joint_Field_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Joint Field Work</label>
        <referenceTo>Joint_Field_Work__c</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/classes/ClsPhysicanVisit.cls
/**
 * 
 *   This classs queries RecordTypes for Physican Visit and keeps in along with request   
 *
 *    Author         |Author-Email                           |Date       |Comment
 *    ---------------|-------------------------------------- |-----------|--------------------------------------------------
 *    Harvin         |harvin.vincent@listertechnologies.com  |04.10.2010 |First draft (This class createed to avoid TOO Many SOQL Queries error 
 *
 */
public class ClsPhysicanVisit {
    public static Map<String, String> map_staticRecordType = new Map<String, String>();
    public static Map<String, RecordType> map_staticRecordTypeObj = new Map<String, RecordType>();
    
    public static void getPhysicanVisitRecordTypes() {
    if (map_staticRecordType != null && map_staticRecordType.size() < 1) {
       for (RecordType oRecordType : [SELECT 
                        Id,
                        Name,
                        Sobjecttype
                       FROM 
                        RecordType
                       WHERE
                        Sobjecttype 
                       IN   
                            ('Joint_Field_Work__c', 'Event', 'Task', 'Physician_Visit__c',
                         'Monthly_Implantation_Detail__c')
                       AND
                        Name
                       IN
                        ('INDSU', 'APACSU', 'INDSU Task','INDSU Sales Planned', 'INDSU Sales Unplanned',
                        'THASU Sales Planned', 'THASU Sales Unplanned',
                        'THASU Service Planned', 'THASU Service Unplanned',
                        'APACSU Sales Planned','APACSU Sales Unplanned',
                        'INDSU Monthly Implantation Detail','APACSU Monthly Implantation Detail',
                        'APACSU Joint Field Work','APACSU Service Engineer','APACSU Technical Service')//Add 2 New Record Type of Physician visit   Gordon 2012-8-7 
                       ORDER BY Sobjecttype]) {
        map_staticRecordType.put(oRecordType.Sobjecttype + '-' + oRecordType.Name, oRecordType.Id);
        map_staticRecordTypeObj.put(oRecordType.Sobjecttype + '-' + oRecordType.Name, oRecordType);
        
    }
     }
   }    

}