B&L QA/objects/Order_Header__c.object
<CustomObject>
    <description>NORDCSS: Stores the Order Header information for orders. Used for creation of new orders, and also as a holding place for back orders in order that track and trace can take place speedily inside salesforce.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Ship To Account on an order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NORSE</fullName>
                </value>
                <value>
                    <fullName>NORNO</fullName>
                </value>
                <value>
                    <fullName>NORDK</fullName>
                </value>
                <value>
                    <fullName>NORFI</fullName>
                </value>
                <value>
                    <fullName>UNKGD</fullName>
                </value>
                <value>
                    <fullName>NETPR</fullName>
                </value>
                <value>
                    <fullName>FRANC</fullName>
                </value>
                <value>
                    <fullName>BELGM</fullName>
                </value>
                <value>
                    <fullName>ITACM</fullName>
                </value>
                <value>
                    <fullName>SPACM</fullName>
                </value>
                <value>
                    <fullName>SPACI</fullName>
                </value>
                <value>
                    <fullName>PORTU</fullName>
                </value>
                <value>
                    <fullName>DMBLV</fullName>
                </value>
                <value>
                    <fullName>SWICM</fullName>
                </value>
                <value>
                    <fullName>AUSTR</fullName>
                </value>
                <value>
                    <fullName>BLUSA</fullName>
                </value>
                <value>
                    <fullName>CANAD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Name__c</fullName>
        <description>This is the name of the person calling in with the order.
Mandatory if the order comes by phone.</description>
        <label>Caller Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Freight Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Delivery__c</fullName>
        <description>Indicates whether an address override is for a home delivery or not.</description>
        <label>Home Delivery?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy System ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Entered_By__c</fullName>
        <description>Contains the name of the user who entered the order. Populated by integration from peoplesoft.</description>
        <label>Order Entered By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Group__c</fullName>
        <label>Order Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>STD</fullName>
                    <default>true</default>
                    <label>STD</label>
                </value>
                <value>
                    <fullName>CAMP</fullName>
                </value>
                <value>
                    <fullName>FOC</fullName>
                </value>
                <value>
                    <fullName>FOCRPL</fullName>
                </value>
                <value>
                    <fullName>LEVAVT</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Source__c</fullName>
        <description>This is the origin of the order.</description>
        <label>Order Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>FAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SETID__c</fullName>
        <externalId>true</externalId>
        <label>SETID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Order_Status__c</fullName>
        <description>Used to manage the integration of orders
Values to be determined.</description>
        <label>SF Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_To_ID__c</fullName>
        <label>Ship To ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/Trgcase_BIU_populateOrderEnteredBy.cls
/**
* 
*   Test class for trigger "case_BIU_populateOrderEnteredBy"
* 
*    Author         |Author-Email                   |Date       |Comment
*    ---------------|-------------------------------|-----------|--------------------------------------------------
*    S Cardinali    |samantha.cardinali@bausch.com  |04.08.2010 |First draft
*
*/
@isTest
private class Trgcase_BIU_populateOrderEnteredBy {
  static testMethod void testcase_BIU_populateOrderEnteredBy() {

    RecordType rtShipTo = [SELECT Id From RecordType Where Name = 'Ship To Account' And SObjectType = 'Account' limit 1];
    RecordType rtEMEA = [Select Id, Name From RecordType Where Name = 'EMEA Service Case' And SObjectType = 'Case' limit 1];
    
    //Insert Account
    Account testACC = new Account (
        Name = 'SCTEST123',
        RecordType = rtShipTo,
        Ship_To_Id__c = '12345678',
        ShippingCity = 'London',
        ShippingPostalCode = '12345'
        );
    insert testACC;
        
    Account testAccSelect = [Select Id, Name, OwnerId, Owner.Name from Account where Id =: testAcc.Id];
        
    //Insert Order_Header__c
      Order_Header__c testOH = new Order_Header__c (
        Account__c = testACC.Id,
        Ship_To_ID__c = '12345678',
        SETID__c = 'NORSE',
        Business_Unit__c = 'NORSE',
        Order_Date__c = System.today(),
        Caller_Name__c = 'SCTest',
        Order_Source__c = 'PHONE',
        Order_Group__c = 'STD',
        Home_Delivery__c = 'No',
        Freight_Override__c = false,
        Order_Status__c = 'Open',
        SF_Order_Status__c = 'Saved',
        order_entered_by__c = 'CARDINS',
        Name = 'NORSE-000000010',
        legacy_system_id__c = 'NORSE000000010'
        );
      insert testOH;
      
      //Insert Case
      Case testCase = new Case (
          Origin = 'Web', 
          RecordTypeId = rtEMEA.id, 
          AccountId = testACC.id, 
          Contact_Name__c = 'EMEA Tester', 
          Domestic_or_International_Order__c = 'Domestic', 
          Solved_on_First_Call__c = 'Yes', 
          Category__c = 'Customer Service', 
          Reason__c = 'Account Change', 
          Status = 'Open',
          Order__c = 'NORSE-0000000010'
      );
      insert testCase;
      
    }
}