B&L QA/objects/Order_Header__c.object
<CustomObject>
    <description>NORDCSS: Stores the Order Header information for orders. Used for creation of new orders, and also as a holding place for back orders in order that track and trace can take place speedily inside salesforce.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Ship To Account on an order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NORSE</fullName>
                </value>
                <value>
                    <fullName>NORNO</fullName>
                </value>
                <value>
                    <fullName>NORDK</fullName>
                </value>
                <value>
                    <fullName>NORFI</fullName>
                </value>
                <value>
                    <fullName>UNKGD</fullName>
                </value>
                <value>
                    <fullName>NETPR</fullName>
                </value>
                <value>
                    <fullName>FRANC</fullName>
                </value>
                <value>
                    <fullName>BELGM</fullName>
                </value>
                <value>
                    <fullName>ITACM</fullName>
                </value>
                <value>
                    <fullName>SPACM</fullName>
                </value>
                <value>
                    <fullName>SPACI</fullName>
                </value>
                <value>
                    <fullName>PORTU</fullName>
                </value>
                <value>
                    <fullName>DMBLV</fullName>
                </value>
                <value>
                    <fullName>SWICM</fullName>
                </value>
                <value>
                    <fullName>AUSTR</fullName>
                </value>
                <value>
                    <fullName>BLUSA</fullName>
                </value>
                <value>
                    <fullName>CANAD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Name__c</fullName>
        <description>This is the name of the person calling in with the order.
Mandatory if the order comes by phone.</description>
        <label>Caller Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_PO_No__c</fullName>
        <description>Custoemr PO No. if the order relates to just one PO number, all the line items should be updated to reflect this value. Otherwise the PO number should be entered at each line item by the CSR for the different Customer PO numbers included in the one order.</description>
        <label>Customer PO No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Freight Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Delivery__c</fullName>
        <description>Indicates whether an address override is for a home delivery or not.</description>
        <label>Home Delivery?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy System ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Entered_By__c</fullName>
        <description>Contains the name of the user who entered the order. Populated by integration from peoplesoft.</description>
        <label>Order Entered By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Group__c</fullName>
        <label>Order Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>STD</fullName>
                    <default>true</default>
                    <label>STD</label>
                </value>
                <value>
                    <fullName>CAMP</fullName>
                </value>
                <value>
                    <fullName>FOC</fullName>
                </value>
                <value>
                    <fullName>FOCRPL</fullName>
                </value>
                <value>
                    <fullName>LEVAVT</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Source__c</fullName>
        <description>This is the origin of the order.</description>
        <label>Order Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>FAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Ref_No__c</fullName>
        <description>If the patient reference no. is added at the order header this should be reflected across all line items. Otherwise, the patient reference number should be entered by the CSR at order line level to reflect which patient each order line relates to.</description>
        <label>Patient Ref. No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ref_Order_Number__c</fullName>
        <description>To contain the Web &quot;W&quot; or &quot;S&quot; reference number.</description>
        <label>Ref Order Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SETID__c</fullName>
        <externalId>true</externalId>
        <label>SETID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Order_Status__c</fullName>
        <description>Used to manage the integration of orders
Values to be determined.</description>
        <label>SF Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_To_ID__c</fullName>
        <label>Ship To ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Order_Line_Item__c.object
<CustomObject>
    <description>NORDCSS: This is the object which holds the line items of orders.</description>
    <fields>
        <fullName>Customer_PO_No__c</fullName>
        <label>Customer PO No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>Displays the line number for all order line items</description>
        <label>Item No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legacy_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy System ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lot_Serial_ID__c</fullName>
        <description>Populated with ps_bl_ordline_chld.SERIAL_ID for consignment orders.</description>
        <label>Lot/Serial ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Group__c</fullName>
        <label>Order Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>STD</fullName>
                    <default>true</default>
                    <label>STD</label>
                </value>
                <value>
                    <fullName>CAMP</fullName>
                </value>
                <value>
                    <fullName>FOC</fullName>
                </value>
                <value>
                    <fullName>FOCRPL</fullName>
                </value>
                <value>
                    <fullName>LEVAVT</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order_Header__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PS_Product_SKU__c</fullName>
        <description>This field will be used in integration for pushing the Peoplesoft SKU back into Peoplesoft when new orders are created in Salesforce.</description>
        <label>PS Product SKU</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Ref_No__c</fullName>
        <label>Patient Ref. No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product SKU</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_From__c</fullName>
        <label>Ship From</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EURLC</fullName>
                    <default>true</default>
                    <label>EURLC</label>
                </value>
                <value>
                    <fullName>EURCD</fullName>
                </value>
                <value>
                    <fullName>VCLSU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OL-{MM}{000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Shipping_History__c.object
<CustomObject>
    <description>NORDCSS: Stores the Shipping History from Peoplesoft relating to Orders.</description>
    <fields>
        <fullName>Legacy_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line Item</label>
        <referenceTo>Order_Line_Item__c</referenceTo>
        <relationshipLabel>Shipping History</relationshipLabel>
        <relationshipName>Shipping_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order_Header__c</referenceTo>
        <relationshipLabel>Shipping History</relationshipLabel>
        <relationshipName>Shipping_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Date__c</fullName>
        <label>Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Signed_for_By__c</fullName>
        <label>Signed for By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Shipping History</label>
    <nameField>
        <displayFormat>SH-{YY}{0000000}</displayFormat>
        <label>Shipping History Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B&L QA/classes/CtrlOrderTracking_Test.cls
/**     
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 *
 *
 *      Author           |Author-Email                      |Date       |Comment
 *      -----------------|----------------------------------|-----------|--------------------------------------------------
 *      Dennis Flüchter  |dennis.fluechter@itbconsult.com   |21.10.2009 |First draft
 *      Dennis Flüchter  |dennis.fluechter@itbconsult.com   |09.08.2010 |Modifications for BU picklist, CustomerPO/PatientRef
 *      Dan Wood         |Dan.Wood@Bausch.com               |18.04.2013 |Create Case link - add Invoice and CarrierID GCM210636
 *
 */
 
@isTest 
private class CtrlOrderTracking_Test {

    static testMethod void CtrlOrderTracking_TestNew() {
        System.debug('TEST NEW');
        
        //RecordType ShipToRC = [SELECT Id From RecordType Where Name = 'Ship To Account' limit 1];
        Id ShipToRC = ClsUtility.getRecordTypeId('Account','Ship To Account');
        
        //Insert Account
        Account testACC = new Account (
            Name = 'DFTEST123',
            RecordTypeId = ShipToRC,
            Ship_To_Id__c = 'DF12345',
            ShippingCity = 'London',
            ShippingPostalCode = '12345'
            );
        insert testACC;
        
        Account testAccSelect = [Select Id, Name, OwnerId, Owner.Name from Account where Id =: testAcc.Id];
        System.debug('OWNER: ' + testAccSelect.Owner.Name);
        
        //Insert Order_Header__c
            Order_Header__c testOH = new Order_Header__c (
            Account__c = testACC.Id,
            Ship_To_ID__c = 'DF12345',
            SETID__c = 'NORSE',
            Business_Unit__c = 'NORSE',
            Order_Date__c = System.today(),
            Caller_Name__c = 'SCTest',
            Order_Source__c = 'PHONE',
            Order_Group__c = 'STD',
            Customer_PO_No__c = 'TestLineItemNoTrigger-OH12345',
            Home_Delivery__c = 'No',
            Freight_Override__c = false,
            Order_Status__c = 'Open',
            SF_Order_Status__c = 'Saved',
            order_entered_by__c = 'DENNIS',
            Name = 'VCUCM-000000010',
            Ref_Order_Number__c = '1230a'
            );
            insert testOH;
            
            Order_Header__c testOHSelect = [Select Id, Name, OwnerId, Owner.Name from Order_Header__c where Id =: testOH.Id];
            System.debug('ORDER NAME: ' + testOHSelect.Name);
            
            
            //Insert Order_Line_Item_c
            Order_Line_Item__c testOL = new Order_Line_Item__c (
            Order__c = testOH.Id,
            PS_Product_SKU__c = 'SDD+020090PKR',
            Lot_Serial_ID__c = 'ABC123',
            Quantity__c = 1,
            Item__c = 1,
            Ship_From__c = 'EURLC',
            Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
            Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
            );
            insert testOL;
            
            Order_Line_Item__c testOlSelect = [Select Id, Name from Order_Line_Item__c where Id =: testOL.Id];
            System.debug('OLI NAME: ' + testOLSelect.Name);
                    
    }
    
    
    static testMethod void CtrlOrderTracking_Test() {
        
        //RecordType ShipToRC = [SELECT Id From RecordType Where Name = 'Ship To Account' limit 1];
        Id ShipToRC = ClsUtility.getRecordTypeId('Account','Ship To Account');
        
        List<Shipping_History__c> list_shipments = new List<Shipping_History__c>();
        
        Profile pUserProfile = [SELECT Id From Profile Where Name = 'BL: System Administrator' Limit 1];  
        //Create a test user
        User testUser = new User (
            Alias = 'testus',
            Email = 'testuser123@bausch.com',
            Emailencodingkey = 'UTF-8',
            Lastname = 'User',
            Firstname = 'Test',
            Languagelocalekey = 'de',
            Localesidkey = 'de',
            Profileid = pUserProfile.Id,
            isActive = true,
            Timezonesidkey = 'America/New_York',
            Username = 'testuser123@bausch.com'
        );
        
        insert testUser;
        
        List<Product2> list_products = [Select Id, Name from Product2 where isActive = true limit 10];      
        
        //Insert Account
        Account testACC = new Account (
            Name = 'DFTEST123',
            RecordTypeId = ShipToRC,
            Ship_To_Id__c = 'DF12345',
            ShippingCity = 'London',
            ShippingPostalCode = '12345'
            );
        insert testACC;
        
        //System.runAs(testUser) {        
            //Insert Order_Header__c
            Order_Header__c testOH = new Order_Header__c (
                Account__c = testACC.Id,
                Ship_To_ID__c = 'DF12345',
                SETID__c = 'NORSE',
                Business_Unit__c = 'NORSE',
                Order_Date__c = System.today(),
                Caller_Name__c = 'SCTest',
                Order_Source__c = 'PHONE',
                Order_Group__c = 'STD',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OH12345',
                Home_Delivery__c = 'No',
                Freight_Override__c = false,
                Order_Status__c = 'Open',
                SF_Order_Status__c = 'Saved',
                order_entered_by__c = 'DENNIS',
                Name = 'VCUCM-000000001',
                Ref_Order_Number__c = '1231a'
                );
            insert testOH;
            
            Order_Header__c OH = [Select Id, OwnerId, Owner.Name from Order_Header__c where Id =: testOH.Id];
            System.debug('OWNER: ' + OH.Owner.Name);
            
            
            //Insert Order_Line_Item_c
            Order_Line_Item__c testOL = new Order_Line_Item__c (
                Order__c = testOH.Id,
                PS_Product_SKU__c = list_products[0].Id,                
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL;
            
            Order_Line_Item__c testOL2 = new Order_Line_Item__c (
                Order__c = testOH.Id,
                PS_Product_SKU__c = list_products[1].Id,
                //PS_Product_SKU__c = 'SDD+020030PKR',
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL2;
            
            Order_Line_Item__c testOL3 = new Order_Line_Item__c (
                Order__c = testOH.Id,
                PS_Product_SKU__c = list_products[2].Id,
                //PS_Product_SKU__c = 'SDD+020010PKR',
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL3;
            
            Shipping_History__c testSH = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '1',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1234',
                Invoice_No__c = 'IDF1234',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH.Id,
                Order_Line_Item__c = testOL.Id
                );
            
            insert testSH;
            list_shipments.add(testSH);
            
            Shipping_History__c testSH2 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '2',
                Shipment_Status__c = 'On Hold', 
                Pack_List_No__c = 'DF1234',
                Invoice_No__c = 'IDF1234',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH.Id,
                Order_Line_Item__c = testOL2.Id
                );
            
            insert testSH2;
            list_shipments.add(testSH2);
            
            Shipping_History__c testSH3 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '3',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1235',
                Invoice_No__c = 'IDF1235',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH.Id,
                Order_Line_Item__c = testOL3.Id
                );
            
            insert testSH3;
            list_shipments.add(testSH3);
            
            Shipping_History__c testSH4 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '4',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1236',
                Invoice_No__c = 'IDF1236',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH.Id,
                Order_Line_Item__c = testOL3.Id
                );
            
            insert testSH4;
            list_shipments.add(testSH4);
            
            //second sequence
            Order_Header__c testOH2 = new Order_Header__c (
                Account__c = testACC.Id,
                Ship_To_ID__c = 'DF12345',
                SETID__c = 'NORSE',
                Business_Unit__c = 'NORSE',
                Order_Date__c = System.today() - 1,
                Caller_Name__c = 'SCTest',
                Order_Source__c = 'PHONE',
                Order_Group__c = 'STD',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OH12345',
                Home_Delivery__c = 'No',
                Freight_Override__c = false,
                Order_Status__c = 'Open',
                SF_Order_Status__c = 'Saved',
                order_entered_by__c = 'DENNIS',
                Name = 'VCUCM-000000002',
                Ref_Order_Number__c = '1232a'
                );
            insert testOH2;
            //Insert Order_Line_Item_c
            Order_Line_Item__c testOL4 = new Order_Line_Item__c (
                Order__c = testOH2.Id,
                PS_Product_SKU__c = list_products[0].Id,
                //PS_Product_SKU__c = 'SDD+020090PKR',
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL4;
            
            Order_Line_Item__c testOL5 = new Order_Line_Item__c (
                Order__c = testOH2.Id,
                PS_Product_SKU__c = list_products[1].Id,
                //PS_Product_SKU__c = 'SDD+020030PKR',
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL5;
            
            Order_Line_Item__c testOL6 = new Order_Line_Item__c (
                Order__c = testOH2.Id,
                PS_Product_SKU__c = list_products[2].Id,
                //PS_Product_SKU__c = 'SDD+020010PKR',
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL6;
            
            Shipping_History__c testSH5 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '5',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1237',
                Invoice_No__c = 'IDF1237',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH2.Id,
                Order_Line_Item__c = testOL4.Id
                );
            
            insert testSH5;
            list_shipments.add(testSH5);
            
            Shipping_History__c testSH6 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '6',
                Shipment_Status__c = 'On Hold', 
                Pack_List_No__c = 'DF1237',
                Invoice_No__c = 'IDF1237',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH2.Id,
                Order_Line_Item__c = testOL5.Id
                );
            
            insert testSH6;
            list_shipments.add(testSH6);
            
            Shipping_History__c testSH7 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '7',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1238',
                Invoice_No__c = 'IDF1238',
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH2.Id,
                Order_Line_Item__c = testOL6.Id
                );
            
            insert testSH7;
            list_shipments.add(testSH7);
            
            Shipping_History__c testSH8 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '8',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1238', 
                Invoice_No__c = 'IDF1238',           
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH2.Id,
                Order_Line_Item__c = testOL6.Id
                );
            
            insert testSH8;
            list_shipments.add(testSH8);
            
            Shipping_History__c testSH9 = new Shipping_History__c (
                Shipment_Date__c = System.today(),
                Signed_for_By__c = 'SCTestMatchKeyTrigger12345',
                Legacy_System_ID__c = testOH.Business_Unit__c + testOH.Ship_To_ID__c + '9',
                Shipment_Status__c = 'On Hold',
                Pack_List_No__c = 'DF1230', 
                Invoice_No__c = 'IDF1230',           
                Quantity_Allocated__c = 2,
                Quantity_Backordered__c = 0,
                Quantity_Shipped__c = 0,
                Order__c = testOH2.Id,
                Order_Line_Item__c = testOL6.Id
                );
            
            insert testSH9;
            list_shipments.add(testSH9);
            
            //second sequence
            Order_Header__c testOH3 = new Order_Header__c (
                Account__c = testACC.Id,
                Ship_To_ID__c = 'DF12345',
                SETID__c = 'NORSE',
                Business_Unit__c = 'VCUCM',
                Order_Date__c = System.today() - 2,
                Caller_Name__c = 'SCTest',
                Order_Source__c = 'PHONE',
                Order_Group__c = 'STD',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OH12345',
                Home_Delivery__c = 'No',
                Freight_Override__c = false,
                Order_Status__c = 'Open',
                SF_Order_Status__c = 'Saved',
                order_entered_by__c = 'DENNIS',
                Name = 'VCUCM-000000003',
                Ref_Order_Number__c = '123b'
                );
            insert testOH3;
            
            //Insert Order_Line_Item_c
            Order_Line_Item__c testOL10 = new Order_Line_Item__c (
                Order__c = testOH3.Id,
                PS_Product_SKU__c = list_products[3].Id,
                //PS_Product_SKU__c = 'SDD+020090PKR',
                Quantity__c = 1,
                Item__c = 1,
                Ship_From__c = 'EURLC',
                Patient_Ref_No__c = 'TestLineItemNoTrigger-OL12345',
                Customer_PO_No__c = 'TestLineItemNoTrigger-OL12345'
                );
            insert testOL10;
            
            /*query records for order search*/
            /*List<Shipping_History__c> list_shipments = [Select s.Id, s.Invoice_No__c, s.Order__c, s.Order_Line_Item__c, s.Pack_List_No__c, 
                s.Tracking_No__c, s.Order__r.Ship_To_ID__c from Shipping_History__c s 
                where Pack_List_No__c != null limit 5];
            System.debug('--> Shipments found: ' + list_shipments.size());
            */
            
            /*query Account data*/
            /*
            Account acc = [Select a.Bill_To__c, a.Bill_To_Address_1__c, a.Bill_To_Address_2__c, a.Bill_To_Credit_Hold__c, 
                a.Bill_To_Credit_Hold_Flag__c, a.Bill_To_Name__c, a.Bill_To_SETID_CUSTID__c, a.BillingCity, a.BillingCountry, 
                a.BillingPostalCode, a.BillingState, a.BillingStreet, a.Business_Unit__c, a.CurrencyIsoCode, a.Description, a.Fax, 
                a.Id, a.Name, a.Phone, a.Preferred_Carrier__c, a.Preferred_Ship_Via__c, a.Primary_Ship_To__c, a.RecordTypeId, 
                a.RecordType.Name, a.SETID__c, a.Ship_To_Address_1__c, a.Ship_To_Address_2__c, a.Ship_To_Id__c, a.ShippingCity, 
                a.ShippingCountry, a.ShippingPostalCode, a.ShippingState, a.ShippingStreet from Account a 
                where a.Ship_To_Id__c = : list_shipments[0].Order__r.Ship_To_ID__c limit 1];
            //a.RecordType.Name = 'Ship To Account' and a.SETID__c = 'NORSE' 
            System.debug('--> Account found: ' + acc.Name);
            System.debug('--> If of Account found: ' + acc.Id);
            */
            
            PageReference pageRef = new PageReference('/apex/CtrlOrderTracking_Search');
            //?retURL=%2Fa0H%2Fo&save_new=1&setid=&sfdc.override=1'
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('setId', testACC.Ship_To_Id__c);
                    
            //define Controller     
            //ApexPages.StandardController Controller = new ApexPages.StandardController();
            
            CtrlOrderTracking clsTest = new CtrlOrderTracking();                
            
            /*simulate FindAccount*/
            clsTest.searchField = testACC.Name;
            clsTest.SOSLsearch();
            clsTest.RowClicked();
            
            /*simulate search without search criteria and too huge date range*/
            clsTest.clearSearchFields();
            clsTest.dummyHeaderFrom.Order_Date__c = Date.today().addDays(-30);
            clsTest.search();
            clsTest.clearSearchFields();
            clsTest.search();

            /*simulate customerpoline search*/            
            clsTest.clearSearchFields();            
            clsTest.shipToId = testACC.Ship_To_Id__c;            
            clsTest.customerPoLine = 'TestLineItemNoTrigger-OL12345';            
            clsTest.dummyHeaderFrom.Order_Date__c = Date.today().addDays(7);            
            clsTest.dummyHeaderTo.Order_Date__c = Date.today();            
            clsTest.search();
            
            clsTest.shipToId = testACC.Ship_To_Id__c;
            /*simulate to create a new order*/
            clsTest.directToOrderCreation();
            
            Integer i = -1; //count variable for forLoop
            //for (Shipping_History__c ship : list_shipments){
            System.debug('--> before shipment for loop');
            for (Shipping_History__c ship : list_shipments){
                i++;
                System.debug('--> # Ship i: ' + i);
                
                /*set search fields for order header*/
                System.debug('QUERY OH for SH');
                Order_Header__c header = [Select Id, Name, Customer_PO_No__c, Order_Entered_By__c, Ref_Order_Number__c from Order_Header__c where Id = : ship.Order__c];
                
                clsTest.dummyHeaderFrom.Order_Date__c = Date.today() - 1; //Date.newInstance(2000, 1, 1);           
                clsTest.shipToAccountName = testACC.Name;
                clsTest.shipToId = testACC.Ship_To_Id__c;
                clsTest.shipToCity = testACC.ShippingCity;
                clstest.shipToPostCode = testACC.ShippingPostalCode;
                
                clsTest.dummyHeaderFrom.Business_Unit__c = 'VCUCM';
                
                clsTest.businessUnit = 'VCUCM'; //added 9th Aug 2010
                clsTest.orderNo = header.Name.replace('VCUCM-', '');                
                System.debug('Header Name: ' + header.Name);
                
                            
                clsTest.invoiceNumber = ship.Invoice_No__c;
                clsTest.packListNo = ship.Pack_List_No__c;
                
                clsTest.refOrderNumber = header.Ref_Order_Number__c;
                
                /*query according line item and set line item search fields*/
                Order_Line_Item__c oli = [Select o.Customer_PO_No__c, o.Id, o.Patient_Ref_No__c, o.Product_SKU__c, 
                    o.Product_SKU__r.Name from Order_Line_Item__c o where Id = :ship.Order_Line_Item__c limit 1];
                
                clsTest.SKU = oli.Product_SKU__r.Name;
                
                System.debug('oli.Customer_PO_No__c: ' + oli.Customer_PO_No__c);
                clsTest.customerPO = header.Customer_PO_No__c;
                
                clstest.patientReference = oli.Customer_PO_No__c; //oli.Patient_Ref_No__c;
                
                clsTest.enteredBy = header.Order_Entered_By__c;
                            
                //if (i > 0 && math.mod(i, 3) == 0){
                    clsTest.search();
                //}
                
                clsTest.expandAll();
                clsTest.next();
                clsTest.previous();
                clsTest.last();
                clsTest.first();
                clsTest.expandAll();
                clsTest.modifySearch();
                clsTest.clearSearchFields(); 
                clsTest.directToOrderCreation(); 
                clsTest.getAccordingHeaderList();
                clsTest.getCaseLinkAccount();
                clsTest.getCaseLinkOrder();
                clsTest.getCaseLinkProduct();
                clsTest.getCaseLinkShipment();
                clsTest.getCaseLinkShippedFrom();
                clsTest.getCaseLinkOrderDate();
                clsTest.getCaseLinkSerialLotID();
                clsTest.getCaseLinkInvoice();
                clsTest.getCaseLinkCarrierID();
                clsTest.getPossibleBusinessUnits();
                clsTest.getTreeHeadline();
                clsTest.getTree();
                clsTest.getRecordStatus();
                clsTest.getListSize();
                clsTest.getSFDCUrl();
                clsTest.getexpandStyle();
                clsTest.getstartPic();
                clsTest.getPSConsignmentLink();
                clsTest.getShippingBoxReport();
                String testStr = clsTest.getPSOrderCreationLink();
                testStr = clsTest.getPSRMALink();   
                
                //Modified after 9th Aug 2010
                testStr = clsTest.getWMSLink();
                testStr = clsTest.getPSRMAWorksheetLink();
                
                //createSOQLCollectionFromSetOfStrings
                Set<String> set_strs = new Set<String>();
                set_strs.add('test1');
                set_strs.add('test2');
                //testStr = clsTest.createSOQLCollectionFromSetOfStrings(set_strs);                     
                
                
            }
        //} // run as testuser         
    }
}