B&L QA/objects/Order_Header__c.object
<CustomObject>
    <description>NORDCSS: Stores the Order Header information for orders. Used for creation of new orders, and also as a holding place for back orders in order that track and trace can take place speedily inside salesforce.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Ship To Account on an order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NORSE</fullName>
                </value>
                <value>
                    <fullName>NORNO</fullName>
                </value>
                <value>
                    <fullName>NORDK</fullName>
                </value>
                <value>
                    <fullName>NORFI</fullName>
                </value>
                <value>
                    <fullName>UNKGD</fullName>
                </value>
                <value>
                    <fullName>NETPR</fullName>
                </value>
                <value>
                    <fullName>FRANC</fullName>
                </value>
                <value>
                    <fullName>BELGM</fullName>
                </value>
                <value>
                    <fullName>ITACM</fullName>
                </value>
                <value>
                    <fullName>SPACM</fullName>
                </value>
                <value>
                    <fullName>SPACI</fullName>
                </value>
                <value>
                    <fullName>PORTU</fullName>
                </value>
                <value>
                    <fullName>DMBLV</fullName>
                </value>
                <value>
                    <fullName>SWICM</fullName>
                </value>
                <value>
                    <fullName>AUSTR</fullName>
                </value>
                <value>
                    <fullName>BLUSA</fullName>
                </value>
                <value>
                    <fullName>CANAD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Name__c</fullName>
        <description>This is the name of the person calling in with the order.
Mandatory if the order comes by phone.</description>
        <label>Caller Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_PO_No__c</fullName>
        <description>Custoemr PO No. if the order relates to just one PO number, all the line items should be updated to reflect this value. Otherwise the PO number should be entered at each line item by the CSR for the different Customer PO numbers included in the one order.</description>
        <label>Customer PO No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Freight Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Delivery__c</fullName>
        <description>Indicates whether an address override is for a home delivery or not.</description>
        <label>Home Delivery?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy System ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Entered_By__c</fullName>
        <description>Contains the name of the user who entered the order. Populated by integration from peoplesoft.</description>
        <label>Order Entered By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Group__c</fullName>
        <label>Order Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>STD</fullName>
                    <default>true</default>
                    <label>STD</label>
                </value>
                <value>
                    <fullName>CAMP</fullName>
                </value>
                <value>
                    <fullName>FOC</fullName>
                </value>
                <value>
                    <fullName>FOCRPL</fullName>
                </value>
                <value>
                    <fullName>LEVAVT</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Source__c</fullName>
        <description>This is the origin of the order.</description>
        <label>Order Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>FAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Ref_No__c</fullName>
        <description>If the patient reference no. is added at the order header this should be reflected across all line items. Otherwise, the patient reference number should be entered by the CSR at order line level to reflect which patient each order line relates to.</description>
        <label>Patient Ref. No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ref_Order_Number__c</fullName>
        <description>To contain the Web &quot;W&quot; or &quot;S&quot; reference number.</description>
        <label>Ref Order Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SETID__c</fullName>
        <externalId>true</externalId>
        <label>SETID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Order_Status__c</fullName>
        <description>Used to manage the integration of orders
Values to be determined.</description>
        <label>SF Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_To_ID__c</fullName>
        <label>Ship To ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Order_Line_Item__c.object
<CustomObject>
    <description>NORDCSS: This is the object which holds the line items of orders.</description>
    <fields>
        <fullName>Customer_PO_No__c</fullName>
        <label>Customer PO No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>Displays the line number for all order line items</description>
        <label>Item No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legacy_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy System ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Group__c</fullName>
        <label>Order Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>STD</fullName>
                    <default>true</default>
                    <label>STD</label>
                </value>
                <value>
                    <fullName>CAMP</fullName>
                </value>
                <value>
                    <fullName>FOC</fullName>
                </value>
                <value>
                    <fullName>FOCRPL</fullName>
                </value>
                <value>
                    <fullName>LEVAVT</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order_Header__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PS_Product_SKU__c</fullName>
        <description>This field will be used in integration for pushing the Peoplesoft SKU back into Peoplesoft when new orders are created in Salesforce.</description>
        <label>PS Product SKU</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Ref_No__c</fullName>
        <label>Patient Ref. No.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_From__c</fullName>
        <label>Ship From</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EURLC</fullName>
                    <default>true</default>
                    <label>EURLC</label>
                </value>
                <value>
                    <fullName>EURCD</fullName>
                </value>
                <value>
                    <fullName>VCLSU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OL-{MM}{000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/CtrlRedirectOrderPageController_Test.cls
/*
 *    Author            |Author-Email                      |Date       |Comment
 *    ------------------|----------------------------------|-----------|--------------------------------------------------
 *    Samantha Cardinali|samantha.cardinali@bausch.com     |22.11.2010 |First draft
 *
 */
 
@isTest
private class CtrlRedirectOrderPageController_Test {
  static testMethod void testCtrlRedirectOrderPageController() {

    RecordType rtShipTo = [SELECT Id, Name FROM RecordType Where SObjectType = 'Account' and Name = 'Ship To Account' LIMIT 1]; 

    //Insert Account
    Account testACC = new Account (
            Name = 'SCTEST123',
            RecordTypeId = rtShipTo.Id,
            Ship_To_Id__c = 'SC345678',
            ShippingCity = 'Rochester',
            ShippingPostalCode = '12345',
            SetID__c = 'BLUSA',
            Legacy_system_id__c = 'BLUSASC345678'
    );
    insert testACC;
       
    //Insert Order_Header__c
    Order_Header__c testOH = new Order_Header__c (
            Account__c = testACC.Id,
            Ship_To_ID__c = 'SC345678',
            SETID__c = 'BLUSA',
            Business_Unit__c = 'VCLSU',
            Order_Date__c = System.today(),
            Caller_Name__c = 'SCTest',
            Order_Source__c = 'PHONE',
            Order_Group__c = 'STD',
            Customer_PO_No__c = 'Test-OH12345',
            Home_Delivery__c = 'No',
            Freight_Override__c = false,
            Order_Status__c = 'Open',
            SF_Order_Status__c = 'Saved',
            order_entered_by__c = 'CARDINS',
            Name = 'VCUCM-000000010',
            Ref_Order_Number__c = '1230a'
            );
    insert testOH;
          
    //Insert Order_Line_Item_c
    Order_Line_Item__c testOL = new Order_Line_Item__c (
            Order__c = testOH.Id,
            PS_Product_SKU__c = 'SDD+020090PKR',
            Quantity__c = 1,
            Item__c = 1,
            Ship_From__c = 'VCLSU',
            Patient_Ref_No__c = 'Test-OL12345',
            Customer_PO_No__c = 'Test-OL12345'
    );
    insert testOL;
          
    ApexPages.StandardController sc = new ApexPages.StandardController(testOH);
    CtrlRedirectOrderPageController ext = new CtrlRedirectOrderPageController(sc);
    ApexPages.currentPage().getParameters().put('id',testOH.id);
        ext.getRedir();
   } 
}