B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>IndiaSU field to collect date on which the activity has occurred</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_time__c</fullName>
        <description>IndiaSU field to collect end description</description>
        <label>End time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hours_in_Surgery__c</fullName>
        <description>CHNSU field to capture the duration of time the sales rep is in surgery</description>
        <label>Hours in Surgery</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0.0</fullName>
                    <default>true</default>
                    <label>0.0</label>
                </value>
                <value>
                    <fullName>0.5</fullName>
                </value>
                <value>
                    <fullName>1.0</fullName>
                </value>
                <value>
                    <fullName>1.5</fullName>
                </value>
                <value>
                    <fullName>2.0</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3.0</fullName>
                </value>
                <value>
                    <fullName>3.5</fullName>
                </value>
                <value>
                    <fullName>4.0</fullName>
                </value>
                <value>
                    <fullName>4.5</fullName>
                </value>
                <value>
                    <fullName>5.0</fullName>
                </value>
                <value>
                    <fullName>5.5</fullName>
                </value>
                <value>
                    <fullName>6.0</fullName>
                </value>
                <value>
                    <fullName>6.5</fullName>
                </value>
                <value>
                    <fullName>7.0</fullName>
                </value>
                <value>
                    <fullName>7.5</fullName>
                </value>
                <value>
                    <fullName>8.0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Joint_Call_With_ASM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IndiaSU field to identify the call as a joint call with manager</description>
        <label>Joint Call With ASM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Activity</label>
        <referenceTo>Physician_Visit__c</referenceTo>
        <relationshipLabel>Last Activity</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OT_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <description>India OT Hours capture from Visulaforce Page</description>
        <label>OT Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IndiaSU field to collect physician from activity</description>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planned Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_1__c</fullName>
        <description>India Product 1 capture from Visualforce Page</description>
        <label>Product 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_2__c</fullName>
        <label>Product 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <description>CHNSU field to capture the session of the physician visit</description>
        <label>Session</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>IndiaSU field to collect start time of the call</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>APAC SU field to identify the physician visit status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visit_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sales Rep Visiting call</description>
        <label>Visit Call</label>
        <type>Checkbox</type>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/classes/Test_ScheduleNotifyPhysicianVisitsAES.cls
/**
 * Test Class to test Send Mail for Notifications to Sales Reps and Managers for Open Physician Visit
 *
 *   Author             |Author-Email                                      |Date       |Comment
 *   -------------------|--------------------------------------------------|-----------|--------------------------------------------------
 *   Tarun Solanki      |tarun.solanki@bausch.com                          |18.06.2014 |First Draft 
 *
 * Class -- CtrlNotifyPhysicianVisitsManagersAES
 * CtrlNotifyPhysicianVisitsManagersAES
 * 
 */
@IsTest(SeeAllData=true)
public class Test_ScheduleNotifyPhysicianVisitsAES  {
   //Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
   static String CRON_EXP = '0 0 10 1 12 ? 2017';
   
   public static testmethod void testNotificationEmails() {
      FetchPhysicians();
     //Test.startTest();
        
         //createStoreVisits();
         // Schedule the test job
         String jobId = System.schedule('testBasicScheduledApex11123', CRON_EXP, new clsNotifyOpenPhyMangersSchedulerAES());
    
         // Get the information from the CronTrigger API object
         CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        
         
         jobId = System.schedule('testBasicScheduledApexManager11', CRON_EXP, new clsNotifyOpenPhyMangersSchedulerAES());
         // Get the information from the CronTrigger API object
         ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
         system.debug('***CronTrigger ct' + ct);
     
     //Test.stopTest();
     
    }        
   
   public static testmethod void FetchPhysicians(){
         Test.startTest();
       List<Contact> listContacts = [Select Id, Owner.UserRoleId, AccountID  from contact where AccountId <> null  and Owner.UserRole.Name like 'INDSU Account Owner' limit 1];
       List<User> listSalesRep = [Select id from user where UserRole.Name like 'INDAES Sales Rep%' and isactive = true limit 1];
       system.debug('**** '+listContacts.size());
       system.debug('****listContacts --'+ listContacts + '****listSalesRep --' + listSalesRep);
       
       if(listContacts.size() == 0){
       
       /**********Account **************/
        Account oAccount = new Account();          
        oAccount.OwnerId = UserInfo.getUserId();            
        oAccount.Name = 'Test'; 
        //oAccount.recordTypeId = map_RecordType.get('INDSU Indirect');          
        insert oAccount;

   /**********Contact **************/
        Contact oContact1 = new Contact();           
        oContact1.AccountId = oAccount.Id;                        
        oContact1.LastName = 'Test Contact1';
        //oContact1.recordTypeId = map_RecordType.get('INDSU Contact');   
        insert oContact1 ;  
        
        listContacts = new  List<Contact>();
        listContacts.add(oContact1);                
      }                       
       
       //List<Physician_Visit__c> testpvList = new List<Physician_Visit__c>();               
                             
       Physician_Visit__c oPhysicianVisit = new Physician_Visit__c();                        
       oPhysicianVisit.Activity_Date__c = System.today().addDays(Integer.ValueOf(System.Label.DaysToComplete));
       oPhysicianVisit.Physician__c = listContacts[0].Id;
       oPhysicianVisit.Status__c = 'Open';
       oPhysicianVisit.Session__c = 'AM';
       oPhysicianVisit.Planned_Call__c = false;
       oPhysicianVisit.OwnerId = listSalesRep[0].Id;
       //oPhysicianVisit.Start_Time__c = Datetime.Now();
       //oPhysicianVisit.End_Time__c = Datetime.Now();
       //oPhysicianVisit.Joint_Call_With_ASM__c = False;           
       //oPhysicianVisit.Last_Activity__c=null;
       //oPhysicianVisit.Visit_Call__c = True;
       //oPhysicianVisit.Product_1__c  = 'Akreos MI-60';
       //oPhysicianVisit.Product_2__c = 'Akreos AO';
       //oPhysicianVisit.OT_Hours__c = True; 
       //oPhysicianVisit.Hours_in_Surgery__c = '6.5';              
       //testpvList.add(oPhysicianVisit);      
       
       insert oPhysicianVisit;
       
       Physician_Visit__c oPhysicianVisit1 = new Physician_Visit__c();                        
       oPhysicianVisit1.Activity_Date__c = System.today().addDays(Integer.ValueOf(System.Label.DaysToComplete));
       oPhysicianVisit1.Physician__c = listContacts[0].Id;
       oPhysicianVisit1.Status__c = 'Open';
       oPhysicianVisit1.Session__c = 'AM';
       oPhysicianVisit1.Planned_Call__c = false;
       oPhysicianVisit1.OwnerId = listSalesRep[0].Id;
       //oPhysicianVisit.Start_Time__c = Datetime.Now();
       //oPhysicianVisit.End_Time__c = Datetime.Now();
       //oPhysicianVisit.Joint_Call_With_ASM__c = False;           
       //oPhysicianVisit.Last_Activity__c=null;
       //oPhysicianVisit.Visit_Call__c = True;
       //oPhysicianVisit.Product_1__c  = 'Akreos MI-60';
       //oPhysicianVisit.Product_2__c = 'Akreos AO';
       //oPhysicianVisit.OT_Hours__c = True; 
       //oPhysicianVisit.Hours_in_Surgery__c = '6.5';              
       //testpvList.add(oPhysicianVisit);      
       
       insert oPhysicianVisit1;
        Test.stopTest();
       
       system.debug('***oPhysicianVisit ' + oPhysicianVisit);
       
       
        
       new clsNotifyOpenPhyMangersSchedulerAES();
       /*Test.startTest();
           Batch_NotifyPhysicianVisits controller = new Batch_NotifyPhysicianVisits() ;  
           Integer batchSize = 1;  
           database.executebatch(controller , batchSize);  
       Test.StopTest();*/
   }
   }