B&L QA/objects/Physician_Visit__c.object
<CustomObject>
    <description>APACSU object to collect details during Physician/Surgeon visit.</description>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>IndiaSU field to collect date on which the activity has occurred</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Call_Duration_Mns__c</fullName>
        <description>CHNSU field to collect the time duration taken for the call to complete</description>
        <label>Call Duration Mns</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5mins</fullName>
                </value>
                <value>
                    <fullName>6-10mins</fullName>
                </value>
                <value>
                    <fullName>11-15mins</fullName>
                </value>
                <value>
                    <fullName>16-20mins</fullName>
                </value>
                <value>
                    <fullName>21-25mins</fullName>
                </value>
                <value>
                    <fullName>26-30mins</fullName>
                </value>
                <value>
                    <fullName>31-40mins</fullName>
                </value>
                <value>
                    <fullName>41-50mins</fullName>
                </value>
                <value>
                    <fullName>51-60mins</fullName>
                </value>
                <value>
                    <fullName>1-1.25hrs</fullName>
                </value>
                <value>
                    <fullName>1.25-1.5hrs</fullName>
                </value>
                <value>
                    <fullName>1.5-1.75hrs</fullName>
                </value>
                <value>
                    <fullName>1.75-2hrs</fullName>
                </value>
                <value>
                    <fullName>2-2.5hrs</fullName>
                </value>
                <value>
                    <fullName>2.5-3hrs</fullName>
                </value>
                <value>
                    <fullName>3-3.5hrs</fullName>
                </value>
                <value>
                    <fullName>3.5-4hrs</fullName>
                </value>
                <value>
                    <fullName>4-5hrs</fullName>
                </value>
                <value>
                    <fullName>5-6hrs</fullName>
                </value>
                <value>
                    <fullName>6-8hrs</fullName>
                </value>
                <value>
                    <fullName>&gt;8hrs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Tel__c</fullName>
        <description>APAC CHNSU field:The telephone number of the contact,</description>
        <label>Contact Tel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>APAC CHNSU field:The Contact of the hospital</description>
        <label>Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IndiaSU field to collect physician from activity</description>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Physician Visit</relationshipLabel>
        <relationshipName>Physician_Visit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_No__c</fullName>
        <description>The Number Of Service Requirement.</description>
        <label>Service No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>APAC SU field to identify the physician visit status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Times_in_Surgery__c</fullName>
        <label>Times in Surgery</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>20+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1_8mm_AMO__c</fullName>
        <label>1.8mm - AMO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_Alcon__c</fullName>
        <label>1.8mm - Alcon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_B_L__c</fullName>
        <label>1.8mm - B&amp;L</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_HumanOptics__c</fullName>
        <label>1.8mm - HumanOptics</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_Zeiss__c</fullName>
        <label>1.8mm - Zeiss</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_AMO__c</fullName>
        <label>2.2mm - AMO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_Alcon__c</fullName>
        <label>2.2mm - Alcon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_B_L__c</fullName>
        <label>2.2mm - B&amp;L</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_HumanOptics__c</fullName>
        <label>2.2mm - HumanOptics</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_Zeiss__c</fullName>
        <label>2.2mm - Zeiss</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_AMO__c</fullName>
        <label>2.8mm - AMO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_Alcon__c</fullName>
        <label>2.8mm - Alcon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_B_L__c</fullName>
        <label>2.8mm - B&amp;L</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_HumanOptics__c</fullName>
        <label>2.8mm - HumanOptics</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_Zeiss__c</fullName>
        <label>2.8mm - Zeiss</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Physician Visit</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Physician Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physician Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B&L QA/objects/Service_Product__c.object
<CustomObject>
    <fields>
        <fullName>Call_Result1__c</fullName>
        <label>Call Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>need follow up</fullName>
                </value>
                <value>
                    <fullName>satisfaction, don&apos;t need follow up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Experiences1__c</fullName>
        <label>Experiences</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Physician_Visit__c</fullName>
        <description>APAC CHNSU field:The related Engineer Physician Visit of the service product.</description>
        <label>Physician Visit</label>
        <referenceTo>Physician_Visit__c</referenceTo>
        <relationshipLabel>Service Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product1__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stellaris</fullName>
                </value>
                <value>
                    <fullName>Stellaris PC</fullName>
                </value>
                <value>
                    <fullName>CX1000</fullName>
                </value>
                <value>
                    <fullName>CX2000</fullName>
                </value>
                <value>
                    <fullName>CX3000</fullName>
                </value>
                <value>
                    <fullName>Protege</fullName>
                </value>
                <value>
                    <fullName>Premiere</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1_8mm_AMO__c</fullName>
        <label>1.8mm - AMO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_Alcon__c</fullName>
        <label>1.8mm - Alcon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_B_L__c</fullName>
        <label>1.8mm - B&amp;L</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_HumanOptics__c</fullName>
        <label>1.8mm - HumanOptics</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_8mm_Zeiss__c</fullName>
        <label>1.8mm - Zeiss</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_AMO__c</fullName>
        <label>2.2mm - AMO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_Alcon__c</fullName>
        <label>2.2mm - Alcon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_B_L__c</fullName>
        <label>2.2mm - B&amp;L</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_HumanOptics__c</fullName>
        <label>2.2mm - HumanOptics</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_2mm_Zeiss__c</fullName>
        <label>2.2mm - Zeiss</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_AMO__c</fullName>
        <label>2.8mm - AMO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_Alcon__c</fullName>
        <label>2.8mm - Alcon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_B_L__c</fullName>
        <label>2.8mm - B&amp;L</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_HumanOptics__c</fullName>
        <label>2.8mm - HumanOptics</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_8mm_Zeiss__c</fullName>
        <label>2.8mm - Zeiss</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Service Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/ClsPhysicianVisitAddProductTest.cls
@isTest
private class ClsPhysicianVisitAddProductTest {

    static testMethod void myUnitTest() {
                RecordType ServiceRepType=[select name,Id from RecordType where name='APACSU Technical Service' And SobjectType='Physician_Visit__c' limit 1];
                RecordType EngineerType=[select name,Id from RecordType where name='APACSU Service Engineer' And SobjectType='Physician_Visit__c' limit 1];
                RecordType PhysicianType=[select Id,name from RecordType where SobjectType='Contact' and name='APACSU Contact' limit 1];
                RecordType AccType=[select Id from RecordType where SobjectType='Account' and name='APACSU Direct'];
                
                Account    TestAcc=new Account(RecordTypeId=AccType.Id,name='Test Acc');
                
                Contact Myphy=new Contact(RecordTypeId=PhysicianType.Id,FirstName='Test',LastName='GG',AccountId=TestAcc.Id);
                
                User objUser = [Select Id, Name from User where User.UserRole.Name  like 'INDSU Sales %' and isactive=: true Limit 1];
                
                System.runAs(objuser) {
                     if(ServiceRepType!=null && PhysicianType!=null)
                        {
                            Test.startTest();
                            insert Myphy;
                            
                            List<Physician_Visit__c> listPhysicianVisit = new List<Physician_Visit__c>();
                            
                            Physician_Visit__c testPhyVisit1=new Physician_Visit__c(RecordTypeId=ServiceRepType.Id,Physician__c=Myphy.Id,
                            Activity_Date__c=System.Today()+30,Call_Duration_Mns__c='5mins',Times_in_Surgery__c='3',Status__c='Open');
                            
                            listPhysicianVisit.add(testPhyVisit1);
                            
                            Physician_Visit__c testPhyVisit2=new Physician_Visit__c(RecordTypeId=EngineerType.Id,Status__c='Open',
                            Activity_Date__c=System.Today()+30,Contact__c='Test',Call_Duration_Mns__c='5mins',Service_No__c='111',  Contact_Tel__c='111');
                            listPhysicianVisit.add(testPhyVisit2);

                            insert listPhysicianVisit;
                            
                            Service_Product__c SP=[select Id from Service_Product__c where Physician_Visit__c=:TestPhyVisit1.Id limit 1];
                            system.assertNotEquals(SP,null);    
                            
                            SP.Product1__c='CX1000';SP.Experiences1__c='abc';
                            SP.X1_8mm_Alcon__c=1;SP.X2_2mm_Alcon__c=1;SP.X2_8mm_Alcon__c=1;
                            SP.X1_8mm_AMO__c=2;SP.X2_2mm_AMO__c=2;SP.X2_8mm_AMO__c=2;
                            SP.X1_8mm_B_L__c=3;SP.X2_2mm_B_L__c=3;SP.X2_8mm_B_L__c=3;
                            SP.X1_8mm_HumanOptics__c=4;SP.X2_2mm_HumanOptics__c=4;SP.X2_8mm_HumanOptics__c=4;
                            SP.X1_8mm_Zeiss__c=5;SP.X2_2mm_Zeiss__c=5;SP.X2_8mm_Zeiss__c=5;
                            SP.Call_Result1__c='need follow up';SP.Call_Objective1__c='Bidding support';                
                            update SP;
                            
                            Physician_Visit__c PV1=[select Id,Times_in_Surgery__c,Status__c from Physician_Visit__c where Id=:TestPhyVisit1.Id limit 1];
                            Physician_Visit__c PV2=[select Id,Status__c from Physician_Visit__c where Id=:TestPhyVisit2.Id limit 1];
                            
                            
                            
                            system.assertEquals(PV2.Status__c,'Completed');
                            system.assertEquals(PV1.Status__c,'Completed');
                            
                            PV1.Times_in_Surgery__c='2';
                            update PV1;
                            
                            
                            SP.X1_8mm_Alcon__c=11;SP.X2_2mm_Alcon__c=11;SP.X2_8mm_Alcon__c=11;
                            SP.X1_8mm_AMO__c=22;SP.X2_2mm_AMO__c=22;SP.X2_8mm_AMO__c=22;
                            SP.X1_8mm_B_L__c=33;SP.X2_2mm_B_L__c=33;SP.X2_8mm_B_L__c=33;
                            SP.X1_8mm_HumanOptics__c=44;SP.X2_2mm_HumanOptics__c=44;SP.X2_8mm_HumanOptics__c=44;
                            SP.X1_8mm_Zeiss__c=55;SP.X2_2mm_Zeiss__c=55;SP.X2_8mm_Zeiss__c=55;
                            
                            update SP;   
                            
                            Test.stopTest();                         
                        }
                }
                
    }
}