B&L QA/objects/Price_Agreement_Product__c.object
<CustomObject>
    <description>EMEASU. Products in this pricing agreement.</description>
    <fields>
        <fullName>Pricing_Agreement__c</fullName>
        <description>The pricing agreement to which this product is related. EMEASU.</description>
        <label>Pricing Agreement</label>
        <referenceTo>Pricing_Agreement__c</referenceTo>
        <relationshipLabel>Price Agreement Products</relationshipLabel>
        <relationshipName>Price_Agreement_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Price Agreement Product</label>
    <nameField>
        <label>Price Set ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Agreement Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Pricing_Agreement__c.object
<CustomObject>
    <description>EMEA SU</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account to which this price set / pricing agreement is related. EMEA SU.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pricing Agreements</relationshipLabel>
        <relationshipName>Pricing_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricing Agreement</label>
    <nameField>
        <label>Price Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/TrgPriceAgreements_setAccountAndSearch.cls
/*
* 
*   Test class for triggers "priceAgreementProduct_BI_populateAcct" and "priceAgreement_BIU_populateSearchInfo"
* 
*    Author         |Author-Email                   |Date       |Comment
*    ---------------|-------------------------------|-----------|--------------------------------------------------
*    S Cardinali    |samantha.cardinali@bausch.com  |14.12.2012 |First draft
*
*/

@isTest
private class TrgPriceAgreements_setAccountAndSearch{
  static testMethod void TrgPriceAgreementTriggers_setAccountAndSearch() {

      //Insert Account
      ID rtShipTo = ClsUtility.getRecordTypeId('Account','Ship To Account');
      List<Account> list_Accounts = new List<Account>();
      Account testAccount1 = new Account(Name = 'SCTESTAccount123543',RecordTypeId = rtShipTo,Legacy_System_ID__c = 'UNKGD001234560');
      list_Accounts.add(testAccount1);
      Account testAccount2 = new Account(Name = 'SCTESTAccount543123',RecordTypeId = rtShipTo,Legacy_System_ID__c = 'UNKGD901234561');
      list_Accounts.add(testAccount2);
      try{
        insert list_Accounts;
      } catch(Exception e) {
        System.debug('Error adding Account: ' + e.getMessage());
      }

      //Insert Price Agreement
      Pricing_Agreement__c testPA = new Pricing_Agreement__c (
        Name = 'ABC123DEF456',
        Account__c = list_Accounts.get(0).Id
      );
      try{
        insert testPA;
      } catch(Exception e) {
        System.debug('Error adding testPA: ' + e.getMessage());
      }
      //Insert Price Agreement Product
      Price_Agreement_Product__c testPAP = new Price_Agreement_Product__c (
        Name = 'PAP123ABC345',
        Pricing_Agreement__c = testPA.Id
      );
      try{
        insert testPAP;
      } catch(Exception e) {
        System.debug('Error adding testPAP: ' + e.getMessage());
      }
      //Update PA account
      Pricing_Agreement__c updatePA = [SELECT Id, Account__c FROM Pricing_Agreement__c WHERE Id = :testPA.Id];
      updatePA.Account__c = list_Accounts.get(1).Id;
      Update updatePA;
      //Update PA account to none
      Pricing_Agreement__c updatePAAgain = [SELECT Id, Account__c FROM Pricing_Agreement__c WHERE Id = :testPA.Id];
      updatePAAgain.Account__c = Null;
      Update updatePAAgain;
    }
}