B&L QA/objects/Product_Complaint_Product__c.object
<CustomObject>
    <description>Contains the Products that are associated with Product Complaints (Product Cases)</description>
    <fields>
        <fullName>Carton_Lot_Number__c</fullName>
        <label>Carton Lot Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Product_Complaint_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complaint_Quantity__c</fullName>
        <label>Complaint Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Received_Subsidiary__c</fullName>
        <label>Date Received Subsidiary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Manufacture__c</fullName>
        <description>Populated when a valid Lot Number is found in query to FSCM</description>
        <label>Date of Manufacture</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delete_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Product Complaints, this field indicates whether or not the record has been deleted so that the before delete trigger knows whether or not to send the SOAP message to CW to delete the record.  True = it has been deleted already, false = it has NOT been deleted, and is the default value.</description>
        <label>Delete Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Value of this field is brought back when the Product Lot Number query from FSCM is returned</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fill_Size__c</fullName>
        <label>Fill Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 gm</fullName>
                </value>
                <value>
                    <fullName>3.5 gm</fullName>
                </value>
                <value>
                    <fullName>0.5 mL</fullName>
                </value>
                <value>
                    <fullName>1 mL</fullName>
                </value>
                <value>
                    <fullName>2 mL</fullName>
                </value>
                <value>
                    <fullName>2.5 mL</fullName>
                </value>
                <value>
                    <fullName>5 mL</fullName>
                </value>
                <value>
                    <fullName>10 mL</fullName>
                </value>
                <value>
                    <fullName>15 mL</fullName>
                </value>
                <value>
                    <fullName>30 mL</fullName>
                </value>
                <value>
                    <fullName>118 mL</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>36 Capsules</fullName>
                </value>
                <value>
                    <fullName>28 Count</fullName>
                </value>
                <value>
                    <fullName>32 Count</fullName>
                </value>
                <value>
                    <fullName>30 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>50 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>60 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>120 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>150 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>180 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>50 Tablets</fullName>
                </value>
                <value>
                    <fullName>60 Tablets</fullName>
                </value>
                <value>
                    <fullName>120 Tablets</fullName>
                </value>
                <value>
                    <fullName>240 Tablets</fullName>
                </value>
                <value>
                    <fullName>300 Tablets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Request_for_Product__c</fullName>
        <inlineHelpText>Required if Product Avalability = &quot;Requested&quot;</inlineHelpText>
        <label>Initial Request for Product</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Justification_for_No_Product_Return__c</fullName>
        <description>Required for Pharma if Product Availability = &quot;Return not Required&quot;</description>
        <label>Justification for No Product Return</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Axis__c</fullName>
        <label>Labeled Axis</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Base_Curve__c</fullName>
        <label>Labeled Base Curve</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Cylinder__c</fullName>
        <label>Labeled Cylinder</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Power__c</fullName>
        <label>Labeled Power</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lens_Type_Used__c</fullName>
        <description>For VC Product Complaints, captures the Lens Type Used for LENSCARE complaints for mapping to CATSWeb.</description>
        <label>Lens Type Used</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>For Product Complaints, pulling LOB from Case to send to Product Line Item in CW</description>
        <formula>Text(Case__r.Line_of_Business__c)</formula>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Site__c</fullName>
        <description>This picklist should be filtered based on Product Type, which is an Apex-populated picklist.</description>
        <label>Manufacturing Site</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled by Apex</fullName>
                    <default>true</default>
                    <label>Controlled by Apex</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Peroxide_System_Lens_Case_Returned__c</fullName>
        <description>For VC Product Complaints where Global Name Product = EasySept - Onesept and Product Availability = Returned. For mapping to CATSWeb.</description>
        <label>Peroxide System Lens Case Returned</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_and_Second_Lot__c</fullName>
        <label>Primary and Secondary Pkg - Same Lot #</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Private_Label_Account__c</fullName>
        <label>Private Label Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1-800-Contacts</fullName>
                </value>
                <value>
                    <fullName>Big Lots</fullName>
                </value>
                <value>
                    <fullName>CVS</fullName>
                </value>
                <value>
                    <fullName>Dollar General</fullName>
                </value>
                <value>
                    <fullName>Kmart</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RiteAid</fullName>
                </value>
                <value>
                    <fullName>Safeway</fullName>
                </value>
                <value>
                    <fullName>SiHy 50E</fullName>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Unilens</fullName>
                </value>
                <value>
                    <fullName>Walgreens</fullName>
                </value>
                <value>
                    <fullName>Wal-Mart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Availability__c</fullName>
        <label>Product Availability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Return Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>Text(Case__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <description>Populated by Local Name from the Product Complaint Product Type field</description>
        <label>Product Description</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Value 1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Lot_Number__c</fullName>
        <description>Value of this field is verified to FSCM in the ps_lot_control_inv table for validity</description>
        <label>Product Lot Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Product Number (or unknown)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Automatically populated when user selects value of Product Description.  Apex used to obtain the value from the Product Complaint Product Type object.</description>
        <label>Global Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Received_Open__c</fullName>
        <label>Quantity Received Open</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Received_Sealed__c</fullName>
        <label>Quantity Received Sealed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Received__c</fullName>
        <label>Quantity Received</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_to_be_Returned__c</fullName>
        <label>Quantity to be Returned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>Record Type Name used in the integration to CATSWeb for product complaints.</description>
        <label>Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_CATSWeb__c</fullName>
        <label>Send to CATSWeb</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_in_Use__c</fullName>
        <label>Time in Use</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Use</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Not Used</fullName>
                </value>
                <value>
                    <fullName>Re-Use</fullName>
                </value>
                <value>
                    <fullName>&lt; 1 Month</fullName>
                </value>
                <value>
                    <fullName>1-3 Months</fullName>
                </value>
                <value>
                    <fullName>4-6 Months</fullName>
                </value>
                <value>
                    <fullName>7-12 Months</fullName>
                </value>
                <value>
                    <fullName>&gt; 1 Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/Product_Complaint_Product_View.cls
/*
* Created By : Rohit Aggarwal
* Test Class Name : Test_Product_Complaint_Product_View
* Used for Product View Page
*
*/
public class Product_Complaint_Product_View {
      public Product_Complaint_Product__c PCP {get; set;}
        public boolean isPharma {get;set;}  
        public string objectID;
        public boolean VCOnly {get;set;}
        public boolean valueExist {get;set;}
        public boolean isClosed {get;set;}
        public boolean isEMEAorAPAC {get; set;}               
        public boolean isLencTypeUsed {get;set;}        
        public boolean isPrimaryPackLotNum {get;set;}    
        public boolean isReturned {get;set;}
        public boolean isNotReturned{get;set;}        
        public boolean isRequested{get;set;}         
        public boolean isPrroxideSystem {get;set;}
        
        
        public boolean quantityToBeReturned {get;set;}
        public boolean dateReceivedSubsidiary {get;set;}
        public boolean quantityReceivedOpen {get;set;}
        public boolean quantityReceivedSealed{get;set;}
        public boolean isReturnNotReqested{get;set;}
        public boolean isManufacturingSite {get;set;}
        
        public boolean isVC {get;set;}
          
        public Product_Complaint_Product_View (ApexPages.StandardController controller){
      //    PCP = (Product_Complaint_Product__c) controller.getRecord();
      //    System.debug('Case value is-------------------->' + PCP.Case__c);
        this.objectID = ApexPages.currentPage().getParameters().get('Id');
        VCOnly = false;
        quantityToBeReturned  = false;
        valueExist = false;
        this.isClosed = true;
        this.isEMEAorAPAC = false;
        this.isPharma  = false;
        this.isPrroxideSystem = false;
        isLencTypeUsed   = false;
        isVC  = false;
        isManufacturingSite  = false;
        init();
        }
        
        public Pagereference init()
        {
            PCP = [select id,name,Delete_Trigger__c,Product_Lot_Number__c,Justification_for_No_Product_Return__c,Primary_and_Second_Lot__c,Lens_Type_Used__c,Peroxide_System_Lens_Case_Returned__c ,Carton_Lot_Number__c,Product_Description__c,Private_Label_Account__c,
                          Case__c,Expiration_Date__c,Manufacturing_Site__c,Product_Type__c,Complaint_Quantity__c,Product_Availability__c,
                          Date_Received_Subsidiary__c,Time_in_Use__c,Quantity_Received__c,Quantity_to_be_Returned__c,Quantity_Received_Sealed__c,
                          Date_Received__c,Serial_Number__c ,Quantity_Received_Open__c,Product_Number__c,Fill_Size__c,Initial_Request_for_Product__c,Labeled_Base_Curve__c,Labeled_Power__c,Labeled_Cylinder__c,Date_of_Manufacture__c,Record_Type__c,
                          Labeled_Axis__c,Comments__c,Case__r.Product_Category__c,Case__r.Status,Case__r.Line_of_Business__c,Case__r.Send_to_CATSWeb__c,Local_Comments__c,Case__r.RecordType.name,Case__r.RecordTypeid
                          from Product_Complaint_Product__c where Id = :objectID];
       
          
           if(PCP.Manufacturing_Site__c!=null && PCP.Manufacturing_Site__c!=''){
               isManufacturingSite  = true;
           }else
           {
               isManufacturingSite   = false;
           }
          
          if(PCP.Product_Description__c!='' && PCP.Product_Description__c!=null)
          valueExist = true;
 
          if(PCP.Case__r.RecordType.name.contains('EMEA') || PCP.Case__r.RecordType.name.contains('APAC'))
          {
            isEMEAorAPAC= true;
          } 
          if(PCP.Case__r.Status == 'Closed') 
            this.isClosed = false;    
            
        return null;
        }
           
      
      public pagereference DeleteRecord(){          
            if(PCP.Case__r.status !='Open'){
                if(!test.isRunningTest())                    
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'Once a Product Complaint has been closed, no additional changes may be made. The Product Complaint can be reopened in CATSWeb.'));
                return null;
            }
            else{
                if(PCP.Case__r.Send_to_CATSWeb__c == 'Yes'){
                    if(!test.isRunningTest())  
                    Delete_from_CATSWeb_Batch.sendRequest(PCP.id,'Product_Complaint_Product__c',PCP.Record_Type__c);                                                  
                }
                PCP.Delete_Trigger__c = true;
                try{
                    update PCP;
                    system.debug('Update :'+PCP);
                    delete PCP;
                }Catch(Exception e){
                }
                    
            }           
            pagereference page = new pagereference('/'+PCP.Case__c);
            page.setRedirect(true);
            return page;                                            
      }       
}