B&L QA/objects/Product_Complaint_Product__c.object
<CustomObject>
    <description>Contains the Products that are associated with Product Complaints (Product Cases)</description>
    <fields>
        <fullName>Carton_Lot_Number__c</fullName>
        <label>Carton Lot Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Product_Complaint_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complaint_Quantity__c</fullName>
        <label>Complaint Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Received_Subsidiary__c</fullName>
        <label>Date Received Subsidiary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Manufacture__c</fullName>
        <description>Populated when a valid Lot Number is found in query to FSCM</description>
        <label>Date of Manufacture</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Value of this field is brought back when the Product Lot Number query from FSCM is returned</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fill_Size__c</fullName>
        <label>Fill Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 gm</fullName>
                </value>
                <value>
                    <fullName>3.5 gm</fullName>
                </value>
                <value>
                    <fullName>0.5 mL</fullName>
                </value>
                <value>
                    <fullName>1 mL</fullName>
                </value>
                <value>
                    <fullName>2 mL</fullName>
                </value>
                <value>
                    <fullName>2.5 mL</fullName>
                </value>
                <value>
                    <fullName>5 mL</fullName>
                </value>
                <value>
                    <fullName>10 mL</fullName>
                </value>
                <value>
                    <fullName>15 mL</fullName>
                </value>
                <value>
                    <fullName>30 mL</fullName>
                </value>
                <value>
                    <fullName>118 mL</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>36 Capsules</fullName>
                </value>
                <value>
                    <fullName>28 Count</fullName>
                </value>
                <value>
                    <fullName>32 Count</fullName>
                </value>
                <value>
                    <fullName>30 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>50 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>60 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>120 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>150 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>180 Soft Gels</fullName>
                </value>
                <value>
                    <fullName>50 Tablets</fullName>
                </value>
                <value>
                    <fullName>60 Tablets</fullName>
                </value>
                <value>
                    <fullName>120 Tablets</fullName>
                </value>
                <value>
                    <fullName>240 Tablets</fullName>
                </value>
                <value>
                    <fullName>300 Tablets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Request_for_Product__c</fullName>
        <inlineHelpText>Required if Product Avalability = &quot;Requested&quot;</inlineHelpText>
        <label>Initial Request for Product</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Justification_for_No_Product_Return__c</fullName>
        <description>Required for Pharma if Product Availability = &quot;Return not Required&quot;</description>
        <label>Justification for No Product Return</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Base_Curve__c</fullName>
        <label>Labeled Base Curve</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Cylinder__c</fullName>
        <label>Labeled Cylinder</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labeled_Power__c</fullName>
        <label>Labeled Power</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lens_Type_Used__c</fullName>
        <description>For VC Product Complaints, captures the Lens Type Used for LENSCARE complaints for mapping to CATSWeb.</description>
        <label>Lens Type Used</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Comments__c</fullName>
        <description>For Product Complaints, this will contain the comments in the user&apos;s native language, if they don&apos;t speak English.  It will then have to be translated into English in the &quot;Comments&quot; field</description>
        <label>Local Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Site__c</fullName>
        <description>This picklist should be filtered based on Product Type, which is an Apex-populated picklist.</description>
        <label>Manufacturing Site</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled by Apex</fullName>
                    <default>true</default>
                    <label>Controlled by Apex</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Peroxide_System_Lens_Case_Returned__c</fullName>
        <description>For VC Product Complaints where Global Name Product = EasySept - Onesept and Product Availability = Returned. For mapping to CATSWeb.</description>
        <label>Peroxide System Lens Case Returned</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_and_Second_Lot__c</fullName>
        <label>Primary and Secondary Pkg - Same Lot #</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Private_Label_Account__c</fullName>
        <label>Private Label Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1-800-Contacts</fullName>
                </value>
                <value>
                    <fullName>Big Lots</fullName>
                </value>
                <value>
                    <fullName>CVS</fullName>
                </value>
                <value>
                    <fullName>Dollar General</fullName>
                </value>
                <value>
                    <fullName>Kmart</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RiteAid</fullName>
                </value>
                <value>
                    <fullName>Safeway</fullName>
                </value>
                <value>
                    <fullName>SiHy 50E</fullName>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Unilens</fullName>
                </value>
                <value>
                    <fullName>Walgreens</fullName>
                </value>
                <value>
                    <fullName>Wal-Mart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Availability__c</fullName>
        <label>Product Availability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Return Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <description>Populated by Local Name from the Product Complaint Product Type field</description>
        <label>Product Description</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Value 1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Lot_Number__c</fullName>
        <description>Value of this field is verified to FSCM in the ps_lot_control_inv table for validity</description>
        <label>Product Lot Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Product Number (or unknown)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Automatically populated when user selects value of Product Description.  Apex used to obtain the value from the Product Complaint Product Type object.</description>
        <label>Global Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Received_Open__c</fullName>
        <label>Quantity Received Open</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Received_Sealed__c</fullName>
        <label>Quantity Received Sealed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Received__c</fullName>
        <label>Quantity Received</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_to_be_Returned__c</fullName>
        <label>Quantity to be Returned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_for_Edit_Prior_Value__c</fullName>
        <description>Holds the prior value of the Reason for Edit field, so that the value can be used once the Reason for Edit is blanked.</description>
        <label>Reason for Edit Prior Value</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_for_Edit__c</fullName>
        <description>When Case ha been sent to catsweb, all changes must have a reason for edit.</description>
        <label>Reason for Edit</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Send_to_CATSWeb__c</fullName>
        <label>Send to CATSWeb</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_in_Use__c</fullName>
        <label>Time in Use</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Use</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Not Used</fullName>
                </value>
                <value>
                    <fullName>Re-Use</fullName>
                </value>
                <value>
                    <fullName>&lt; 1 Month</fullName>
                </value>
                <value>
                    <fullName>1-3 Months</fullName>
                </value>
                <value>
                    <fullName>4-6 Months</fullName>
                </value>
                <value>
                    <fullName>7-12 Months</fullName>
                </value>
                <value>
                    <fullName>&gt; 1 Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/objects/Product_Complaint_Product_Type__c.object
<CustomObject>
    <description>Holds values used to populate Product Type and Product Description fields in the Product Complaint (Case) object.</description>
    <fields>
        <fullName>Manufacturing_Site__c</fullName>
        <description>Holds the manufacturing site for this product</description>
        <label>Manufacturing Site</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Product Complaint Product Type</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product Complaint Product Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Complaint Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/Product_Complaint_Product_Edit.cls
/*
* Created By : Rohit Aggarwal
* Test Class Name : Test_Product_Complaint_Controller
* Used for Product object to make it dynamic
*
*/
/*
* Updated By : Jennie Burns - 03/06/2013 - GCM - 207356
* For Pharma - Adverse Event Complaints that dont go to CATSWeb - default required fields
*
*/
public class Product_Complaint_Product_Edit  {

      public Product_Complaint_Product__c PCP {get; set;}
      public boolean isReturned {get; set;}
      public boolean inputReturned{get; set;}
      public string objectID;
      public boolean valueExist {get;set;}
      public list<Product_Complaint_Product_Type__c> AllProdType ;
      public Set<String> AllLocalName;
      public Set<String> AllManufacturing_Site;
      public string LocalName {get; set;}
      public string SiteName {get; set;}
      public String one;
      public boolean isInit;
      public boolean isLot {get; set;}
      public boolean isAccount {get; set;}
      public boolean reason {get; set;}
      public boolean reasonPrior {get; set;}
      public boolean isResnRequire {get; set;}
      public boolean isEMEAorAPAC {get; set;}
      public boolean isClosed {get; set;}
      public boolean isNotClosed {get; set;}
      public boolean isNotReturned {get; set;}
      public boolean isFillSize  {get;set;}
      public boolean isPrimaryPackLotNum {get;set;}    
      public boolean quantityToBeReturned {get;set;}
      public boolean dateReceivedSubsidiary {get;set;}
      public boolean quantityReceivedOpen {get;set;}
      public boolean quantityReceivedSealed{get;set;}
      public boolean isReturnNotReqested{get;set;}
      public boolean isRequested{get;set;}
      public boolean isProductNumber {get;set;}
      public boolean isDisappearOutpanal {get;set;}
     
          
      public Product_Complaint_Product_Edit (ApexPages.StandardController controller)
      {
        this.objectID = ApexPages.currentPage().getParameters().get('Id');

       
        init();
      } 
         /*Get all  Local Names for product description*/
     public List<SelectOption> getLocalNames() 
     {
              List<SelectOption> localVal = new List<SelectOption>();
              localVal.add(new SelectOption('','--None--'));
              if(!AllLocalName.isEmpty())
              {
                list<String> AllLocVals = new list<String>();
                AllLocVals.addall(AllLocalName);
        
                for( integer i=0;i<AllLocVals.size();i++)
                localVal.add(new SelectOption(AllLocVals[i], AllLocVals[i]));
              }
              localVal = sortOptionList(localVal);    
              return localVal;
      }
           
          /*Get all Manufacturing sites*/
       public List<SelectOption> getManSites() 
       {
               List<SelectOption> manSite = new List<SelectOption>();
               if(!AllManufacturing_Site.isEmpty())
               {
                 list<String> AllSiteVals = new list<String>();
                 AllSiteVals.addall(AllManufacturing_Site); 
                 if(AllSiteVals.size()==1)
                 {
                    manSite.add(new SelectOption(AllSiteVals[0], AllSiteVals[0]));
                 }
                 else
                 {
                    manSite.add(new SelectOption('','--None--'));
                    for( integer i=0;i<AllSiteVals.size();i++)
                      manSite.add(new SelectOption(AllSiteVals[i], AllSiteVals[i]));
                 }               
               }
               return manSite;
         } 
                    
       
      public Pagereference init()
      {    
             this.reason = false;
             quantityToBeReturned=false;
            this.reasonPrior = false;
            this.isResnRequire = false;

            isReturned = false;
            this.isNotReturned = true;
            isLot = false;
            isAccount = false;

            valueExist = false;
            isInit = false;
            this.isEMEAorAPAC = false;
            this.isClosed = false;
            this.isNotClosed = false;
            isFillSize   = false;


            isProductNumber = false;
            isDisappearOutpanal = false;
        AllLocalName = new Set<String>();
        AllManufacturing_Site = new Set<String>();
        
            PCP = [select id,name,Product_Lot_Number__c,Product_Number__c ,Justification_for_No_Product_Return__c ,Peroxide_System_Lens_Case_Returned__c,Carton_Lot_Number__c,Initial_Request_for_Product__c ,Fill_Size__c ,Primary_and_Second_Lot__c,Lens_Type_Used__c,Product_Description__c,Private_Label_Account__c,
                          Case__c,Expiration_Date__c,Manufacturing_Site__c,Product_Type__c,Complaint_Quantity__c,Product_Availability__c,
                          Date_Received_Subsidiary__c,Time_in_Use__c,Quantity_Received__c,Quantity_to_be_Returned__c,Quantity_Received_Sealed__c,
                          Date_Received__c,Serial_Number__c,Quantity_Received_Open__c,Labeled_Base_Curve__c,Labeled_Power__c,Labeled_Cylinder__c,
                          Case__r.Contact_Type__c,Date_of_Manufacture__c,Reason_for_Edit__c,Reason_for_Edit_Prior_Value__c,Case__r.Send_to_CATSWeb__c,Local_Comments__c,
                          Labeled_Axis__c,Comments__c,Case__r.Product_Category__c,Case__r.Business_Unit__c,Case__r.Line_of_Business__c,
                          Case__r.RecordType.name,Case__r.RecordTypeid,Record_type__c,Recordtypeid,Case__r.Status  from Product_Complaint_Product__c where Id = :objectID];
                          
           if(PCP.Case__r.Status == 'Closed')
           { 
                 this.isClosed = true;
                 this.isNotClosed = false;    
                return null;
            }
            else{
                 this.isClosed = false;
                 this.isNotClosed = true; 
            }

            if(PCP.Product_Description__c!='' && PCP.Product_Description__c!=null)
            {
               isInit = true;
               one=PCP.Product_Description__c;
               LocalName =PCP.Product_Description__c;
            }
            
             if(PCP.Case__r.RecordType.name.contains('EMEA') || PCP.Case__r.RecordType.name.contains('APAC')){
                isEMEAorAPAC= true;
             }   
             if(PCP.Case__r.Send_to_CATSWeb__c=='Yes') {
                 reason = true;
                 reasonPrior = true;
             }           
             if(PCP.Case__r.Send_to_CATSWeb__c=='Yes' && isEMEAorAPAC == false){
                    isResnRequire = true;               
             }
             try{                 
              AllProdType = [select id,name,Business_Unit__c,Category__c,Local_Name__c,Global_Name__c 
                                                                                  from Product_Complaint_Product_Type__c 
                                                                       where Business_Unit__c =:PCP.Case__r.Business_Unit__c 
                                                                        and Category__c = :PCP.Case__r.Product_Category__c ];                
                
                 if(!AllProdType.isEmpty())
                 {
                    for(Product_Complaint_Product_Type__c pt : AllProdType)
                    {
                        AllLocalName.add(pt.Local_Name__c);
                    }
                 }
                  
                 if(PCP.Manufacturing_Site__c!=null && PCP.Manufacturing_Site__c!=''){
                    
                    getGlobalName();
                    valueExist = true;
                    SiteName = PCP.Manufacturing_Site__c;
                    
                 }
                 
         }catch(exception ex){
            
         }                          
                 return null;
            
                                
      }
   
    public Pagereference getGlobalName()
         {
            SiteName =null;
            if(!isInit)
            one = Apexpages.currentPage().getParameters().get('one');
            System.debug('Value of local one is--------------------->' + one);
            isInit = false;
            list<Product_Complaint_Product_Type__c>  AllManSites = [select id,Global_Name__c,Manufacturing_Site__c 
                                                         from Product_Complaint_Product_Type__c 
                                                         where Local_Name__c =:one and Business_Unit__c =:PCP.Case__r.Business_Unit__c 
                                                         and Category__c =:PCP.Case__r.Product_Category__c
                                                         and Line_of_Business__c =:PCP.Case__r.Line_of_Business__c]; 
           
            System.debug('Man site size is--------------->' +AllManSites.size());
            AllManufacturing_Site = new Set<String>();
            
            if(!AllManSites.isEmpty())
            {
                valueExist = true;
                for(Product_Complaint_Product_Type__c p1 :AllManSites)
                {
                    AllManufacturing_Site.add(p1.Manufacturing_Site__c);
                }
            } else{
                valueExist = false;
            }
            
            list<Product_Complaint_Product_Type__c>  AllGlobalName = [select id,Global_Name__c from Product_Complaint_Product_Type__c 
                                                         where Local_Name__c =:one and Business_Unit__c =:PCP.Case__r.Business_Unit__c]; 
            for(Product_Complaint_Product_Type__c pp :AllGlobalName)
            {
                if(pp.Global_Name__c!=null)
                {
                    PCP.Product_Type__c = pp.Global_Name__c;
                   
                    return null;
                }
            }
         PCP.Product_Type__c = one;
            return null;
         }      
     public Pagereference savemethod()
     {
        Date todayDate = System.today();
       try{
            PCP.Product_Description__c = LocalName;
            if(valueExist==true && SiteName==null){
             ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Manufacturing Site: You must enter a value');
             ApexPages.addMessage(myMsg);
            return null;
            }
            if(PCP.Product_Description__c==null ||PCP.Product_Description__c==''){
             ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Product Description: You must enter a value');
             ApexPages.addMessage(myMsg);
            return null;
            }            
    
             if(PCP.Product_Availability__c == 'returned' && (PCP.Date_Received__c ==null && PCP.Date_Received_Subsidiary__c ==null)){
             ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'For Product Availability Returned: You must enter a value for Date Received or Date Received Subsidiary');
             ApexPages.addMessage(myMsg);
             return null;              
            } 
             if(PCP.Serial_Number__c ==null && PCP.Product_Lot_Number__c ==null){
             ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'You must enter a value for Product Lot Number OR Serial Number ');
             ApexPages.addMessage(myMsg);
             return null;             
            } 
             if(PCP.Date_Received__c > todayDate || PCP.Date_Received_Subsidiary__c >todayDate){
             ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Date Received or Date Received Subsidiary can not be greater than today');
             ApexPages.addMessage(myMsg);
             return null;             
            }            
            PCP.Manufacturing_Site__c = SiteName;  
                     
            if(PCP.Complaint_Quantity__c!=null)
            PCP.Complaint_Quantity_Int__c = String.valueOf(math.round(PCP.Complaint_Quantity__c));
            if(PCP.Quantity_Received__c!=null)
            PCP.Quantity_Received_Int__c = String.valueOf(math.round(PCP.Quantity_Received__c));
            if(PCP.Quantity_Received_Open__c!=null)
            PCP.Quantity_Received_Open_Int__c = String.valueOf(math.round(PCP.Quantity_Received_Open__c));
            if(PCP.Quantity_Received_Sealed__c!=null)
            PCP.Quantity_Received_Sealed_Int__c = String.valueOf(math.round(PCP.Quantity_Received_Sealed__c));
            if(PCP.Quantity_to_be_Returned__c!=null)
            PCP.Quantity_to_be_Returned_Int__c = String.valueOf(math.round(PCP.Quantity_to_be_Returned__c));
            
             /* Assign record type according to case record type*/
        /*
          if(cc[0].RecordTypeId!= null)
            {
                list<RecordType> AllprodRec = new list<RecordType>([select id,name from RecordType where id = :cc[0].RecordTypeId]);
                
                System.debug('---------AllprodRec ------------------------'+AllprodRec);
                
                if(AllprodRec[0].name=='NA SU Product Case' || AllprodRec[0].name=='NA SU Product Case Read Only')
                {
                    PCP.Record_Type__c ='NA SU Product';
                }
                else if(AllprodRec[0].name=='EMEA SU Product Case' || AllprodRec[0].name=='EMEA SU Product Case Read Only')
                {
                    PCP.Record_Type__c ='EMEA SU Product';
                }
            }
        
           if(PCP.RecordTypeId == null)
            {
                list<RecordType> AllprodRec1 = new list<RecordType>([select id,name from RecordType where name = :PCP.Record_Type__c and sobjecttype =:'Product_Complaint_Product__c']);
                PCP.RecordTypeid = AllprodRec1[0].id;
            }
        */
          update PCP;
         }catch(exception ex){

         }   
          Pagereference newpage = new Pagereference('/'+PCP.Case__c);
            newpage.setRedirect(true);
            return newpage;
      }
      
        
         public void requiredSwitch()
         {
            String one1 = Apexpages.currentPage().getParameters().get('first');
            system.debug('one1 one1 --->'+one1 );
         // System.debug('value is-------------------->' + Allprod );
            if(one1 =='Returned'){
                this.isReturned = true  ;
                this.isRequested= false;
                this.isNotReturned = false  ;
                this.isReturnNotReqested= false; 
                quantityToBeReturned=false; 
                inputReturned=true;              
            }
           
              else if(one1=='Requested'){
                     quantityToBeReturned=true;
                     inputReturned=false; 
                      isReturned = false;
                      isNotReturned = true ;
                     isReturnNotReqested  = false;                                          
                 }else if(one1 =='Return not Required'){
                     isReturned= false;
                     inputReturned=false;
                     isNotReturned = true ;
                     quantityToBeReturned=false;                                                           
                     isReturnNotReqested  = true  ;                      
                 }else if(one1=='Not Available'){
                     isReturned = false;
                     isNotReturned = true ;
                     inputReturned=false;
                     quantityToBeReturned=false;
                     isReturnNotReqested  = false;
                 }
                 else if(one1=='None'){
                     isReturned = false;
                     isNotReturned = false;
                     inputReturned=false;
                     quantityToBeReturned=false;
                     isReturnNotReqested  = false;
                 }                     
            
                              
             //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, one1);
             //ApexPages.addMessage(myMsg);           
             //return null;
         }
    // Sorting of select list
    public static List<SelectOption> sortOptionList(List<SelectOption> ListToSort)  {
        
        if(ListToSort == null || ListToSort.size() <= 1) {
            return ListToSort;                  
        }
        
        List<SelectOption> Less = new List<SelectOption>();     
        List<SelectOption> Greater = new List<SelectOption>();  
            
        integer pivot = 0;              
        // save the pivot and remove it from the list       
        SelectOption pivotValue = ListToSort[pivot];        
        ListToSort.remove(pivot);               
        for(SelectOption x : ListToSort) {          
            if(x.getLabel().compareTo(pivotValue.getLabel()) <= 0) {
                Less.add(x);
            } else if(x.getLabel().compareTo(pivotValue.getLabel()) > 0) {
                Greater.add(x);
            }   
        }       
        List<SelectOption> returnList = new List<SelectOption> ();      
        returnList.addAll(SortOptionList(Less));
        returnList.add(pivotValue); 
        returnList.addAll(SortOptionList(Greater)); 
        
        return returnList; 
    }                
 
}