B&L QA/objects/Sample_Product__c.object
<CustomObject>
    <description>Lists of sample products. Originally created for DAS PH, now in use by EMEA SU.</description>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>List of Surgical Level 4 Product Groups for Sampling. Used by EMEA SU.</description>
        <label>Product Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accommodating IOL</fullName>
                </value>
                <value>
                    <fullName>Acrylic IOL</fullName>
                </value>
                <value>
                    <fullName>Anterior Accessories</fullName>
                </value>
                <value>
                    <fullName>Anterior Disposables</fullName>
                </value>
                <value>
                    <fullName>Instruments</fullName>
                </value>
                <value>
                    <fullName>IOL Inserters</fullName>
                </value>
                <value>
                    <fullName>Other Cataract</fullName>
                </value>
                <value>
                    <fullName>Posterior Disposables</fullName>
                </value>
                <value>
                    <fullName>Posterior Other</fullName>
                </value>
                <value>
                    <fullName>Silicone IOL</fullName>
                </value>
                <value>
                    <fullName>SOLTA</fullName>
                </value>
                <value>
                    <fullName>Viscoelastic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity_Requested__c</fullName>
        <description>Used by EMEA SU.</description>
        <label>Quantity Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <description>SKUs for surgical sampling. Used by EMEA SU.</description>
        <label>SKU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Product_Group__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AT50AO-1700</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1750</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1800</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1825</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1850</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1875</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1900</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1925</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1950</fullName>
                </value>
                <value>
                    <fullName>AT50AO-1975</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2000</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2025</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2050</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2075</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2100</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2125</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2150</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2175</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2200</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2250</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2300</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2350</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2400</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2450</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2500</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2550</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2600</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2650</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2700</fullName>
                </value>
                <value>
                    <fullName>AT50AO-2750</fullName>
                </value>
                <value>
                    <fullName>CC100S - Ocucoat 2ml</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <description>Reference to the Sample Request this product sample was created under. Used by EMEA SU.</description>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Products</relationshipLabel>
        <relationshipName>Sample_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Product_Group__c</fullName>
        <description>List of level 5 product groups for surgical sampling. Used by EMEA SU.</description>
        <label>Sub Product Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Group__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>20G Combined Procedure Pack</fullName>
                </value>
                <value>
                    <fullName>20G Combined Proc Pack w/AFI</fullName>
                </value>
                <value>
                    <fullName>20G Posterior Pack</fullName>
                </value>
                <value>
                    <fullName>20G Posterior Pack w/AFI</fullName>
                </value>
                <value>
                    <fullName>23G Combined Procedure Pack</fullName>
                </value>
                <value>
                    <fullName>23G Combined Proc Pack w/AFI</fullName>
                </value>
                <value>
                    <fullName>23G Posterior Pack</fullName>
                </value>
                <value>
                    <fullName>23G Posterior Pack w/AFI</fullName>
                </value>
                <value>
                    <fullName>25G Combined Procedure Pack</fullName>
                </value>
                <value>
                    <fullName>25G Combined Proc Pack w/AFI</fullName>
                </value>
                <value>
                    <fullName>25G Posterior Pack</fullName>
                </value>
                <value>
                    <fullName>25G Posterior Pack w/AFI</fullName>
                </value>
                <value>
                    <fullName>Acrylic Hydrophobic 1pc Asp IO</fullName>
                </value>
                <value>
                    <fullName>Adapt AO</fullName>
                </value>
                <value>
                    <fullName>Akreos MICS</fullName>
                </value>
                <value>
                    <fullName>Amvisc</fullName>
                </value>
                <value>
                    <fullName>Amvisc Plus</fullName>
                </value>
                <value>
                    <fullName>Balanced Salt Solutions</fullName>
                </value>
                <value>
                    <fullName>Cataract Instruments</fullName>
                </value>
                <value>
                    <fullName>Clear + Brilliant</fullName>
                </value>
                <value>
                    <fullName>Crystalens AO</fullName>
                </value>
                <value>
                    <fullName>Crystalens HD500</fullName>
                </value>
                <value>
                    <fullName>Disposable Knives</fullName>
                </value>
                <value>
                    <fullName>Fraxel</fullName>
                </value>
                <value>
                    <fullName>INCISE</fullName>
                </value>
                <value>
                    <fullName>IOL Inserters - EyeCee One MDJ265 single use injector</fullName>
                </value>
                <value>
                    <fullName>IOL Inserters - Hydroport</fullName>
                </value>
                <value>
                    <fullName>IOL Inserters - Microsert</fullName>
                </value>
                <value>
                    <fullName>IOL Inserters - Mport</fullName>
                </value>
                <value>
                    <fullName>IOL Inserters - Mport SI</fullName>
                </value>
                <value>
                    <fullName>Ocucoat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sample Product</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Sample Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/objects/Sample_Request__c.object
<CustomObject>
    <description>Alows the TM to submit requests for samples to be sent to the contact or account. 
Originally created for ECS team. Now changed and used by EMEA SU.</description>
    <fields>
        <fullName>Courier__c</fullName>
        <description>The TM&apos;s preferred courier for this sample delivery. Used by EMEA SU.</description>
        <label>Courier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bring Parcel</fullName>
                </value>
                <value>
                    <fullName>DHL</fullName>
                </value>
                <value>
                    <fullName>ParcelForce</fullName>
                </value>
                <value>
                    <fullName>Polarspeed</fullName>
                </value>
                <value>
                    <fullName>UPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                    <default>true</default>
                    <label>One Time</label>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Submitted</fullName>
                </value>
                <value>
                    <fullName>Request Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Request Issue</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggers the workflow that populates the appropriate CS email address and sends the request email. Used by EMEA SU.</description>
        <inlineHelpText>Only check this box once you have added all of the required Sample Products to the request</inlineHelpText>
        <label>Submit to Customer Services</label>
        <type>Checkbox</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <recordTypes>
        <fullName>EMEA_SU_Sample_Request</fullName>
        <active>true</active>
        <description>Product Sample Request form for EMEA Surgical</description>
        <label>EMEA SU Sample Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/TrgsampleRequest_BIU_validateSubmit.cls
/**
* 
*   Test class for trigger "sampleRequest_BIU_validateSubmit"
* 
*    Author         |Author-Email                   |Date       |Comment
*    ---------------|-------------------------------|-----------|--------------------------------------------------
*    S Cardinali    |samantha.cardinali@bausch.com  |03.08.2010 |First draft
*
*/
@isTest
private class TrgsampleRequest_BIU_validateSubmit {
  static testMethod void testsampleRequest_BIU_validateSubmit() {
  
        RecordType rtAccount = [SELECT Id FROM RecordType WHERE Name = 'Ship To Account' AND SObjectType='Account' Limit 1];
        Profile pUserProfile = [SELECT Id From Profile Where Name = 'EMEASU Territory Manager' Limit 1];
      RecordType rtSampleRequest = [SELECT Id FROM RecordType WHERE DeveloperName = 'EMEA_SU_Sample_Request' AND SObjectType='Sample_Request__c' Limit 1];

        //create account
        Account oTestAccount = new Account(
            Name = 'SC Test Account 1',
            RecordTypeId = rtAccount.Id,
            Legacy_system_id__c = 'UNKGD12345678'  
        );
        try {
            insert oTestAccount;
        } catch(exception e) {
            system.debug('ERROR -- could not create test account.');
        }

        //create user -- with ref to account
        User oTestUser = new User(
            FirstName = 'SCTest123',
            LastName = 'User1',
            Personal_account__c = oTestAccount.Legacy_system_id__c,
            ProfileId = pUserProfile.Id,
            Username = 'sctest123@aplace.com.dev1',
            Email = 'samantha.cardinali@bausch.com',
            Alias = 'sctst123',
            CommunityNickname = 'sctestfromaplacedev1',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        try {
            insert oTestUser;
        } catch(exception e) {
            system.debug('ERROR -- could not create test user.');
        }
    
    system.runas(oTestUser) {
    
            //create sample request (should fail)
            Sample_request__c oTestFailSampleRequest = new Sample_request__c(
                RecordTypeId = rtSampleRequest.Id,
                Frequency__c = 'Weekly',
                Request_status__c = 'New',
                Courier__c = 'ParcelForce',
                Submit_for_approval__c = True
            );
            try {
                insert oTestFailSampleRequest;
            } catch(exception e) {
                system.debug('ERROR -- could not create test sample request.');
            }

            //create sample request (should create)
            Sample_request__c oTestSampleRequest = new Sample_request__c(
                RecordTypeId = rtSampleRequest.Id,
                Frequency__c = 'Weekly',
                Request_status__c = 'New',
                Courier__c = 'ParcelForce',
                Submit_for_approval__c = False
            );
            try {
                insert oTestSampleRequest;
            } catch(exception e) {
                system.debug('ERROR -- could not create test sample request.');
            }

            //update sample request
            oTestSampleRequest.Frequency__c = 'One Time';
            oTestSampleRequest.Submit_for_approval__c = True;
            try {
                update oTestSampleRequest;
            } catch(exception e) {
                system.debug('ERROR -- could not create update sample request.');
            }

            //add product
            Sample_product__c oTestSampleProduct = new Sample_product__c(
                Sample_Request__c = oTestSampleRequest.Id,
                Product_group__c = 'Viscoelastic',
                Sub_Product_Group__c = 'Ocucoat',
                SKU__c = 'CC100S - Ocucoat 2ml',
                Quantity_requested__c = 1.0
            );
            try {
                insert oTestSampleProduct;
            } catch(exception e) {
                system.debug('ERROR -- could not create test sample product.');
            }

            //update sample request
            oTestSampleRequest.Submit_for_approval__c = True;
            try {
                update oTestSampleRequest;
            } catch(exception e) {
                system.debug('ERROR -- could not update test sample request.');
            }
  
    }
  
  }
}