B&L QA/objects/Sample_Request__c.object
<CustomObject>
    <description>Alows the TM to submit requests for samples to be sent to the contact or account. 
Originally created for ECS team. Now changed and used by EMEA SU.</description>
    <fields>
        <fullName>Courier__c</fullName>
        <description>The TM&apos;s preferred courier for this sample delivery. Used by EMEA SU.</description>
        <label>Courier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bring Parcel</fullName>
                </value>
                <value>
                    <fullName>DHL</fullName>
                </value>
                <value>
                    <fullName>ParcelForce</fullName>
                </value>
                <value>
                    <fullName>Polarspeed</fullName>
                </value>
                <value>
                    <fullName>UPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                    <default>true</default>
                    <label>One Time</label>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Submitted</fullName>
                </value>
                <value>
                    <fullName>Request Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Request Issue</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggers the workflow that populates the appropriate CS email address and sends the request email. Used by EMEA SU.</description>
        <inlineHelpText>Only check this box once you have added all of the required Sample Products to the request</inlineHelpText>
        <label>Submit to Customer Services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory_Manager_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The personal account of the Territory Manager who is placing the sample request order and to whom the order should be shipped. Used by EMEA SU.</description>
        <inlineHelpText>Account of the Territory Manager placing the sample request order.</inlineHelpText>
        <label>Territory Manager Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sample Requests (Delivery Account)</relationshipLabel>
        <relationshipName>Sample_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <recordTypes>
        <fullName>EMEA_SU_Sample_Request</fullName>
        <active>true</active>
        <description>Product Sample Request form for EMEA Surgical</description>
        <label>EMEA SU Sample Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B&L QA/classes/TrgSampleRequest_BIU_setTMAcct.cls
/**
* 
*   Test class for trigger "sampleRequest_BIU_setTerritoryManagerAcct"
* 
*    Author         |Author-Email                   |Date       |Comment
*    ---------------|-------------------------------|-----------|--------------------------------------------------
*    S Cardinali    |samantha.cardinali@bausch.com  |13.04.2010 |First draft
*
*/
@isTest
private class TrgSampleRequest_BIU_setTMAcct {
  static testMethod void testSampleRequest_BIU_setTerritoryManagerAcct() {
  
  RecordType rtAccount = [SELECT Id FROM RecordType WHERE Name = 'Ship To Account' AND SObjectType='Account' Limit 1];
  Profile pUserProfile = [SELECT Id From Profile Where Name = 'EMEASU Territory Manager' Limit 1];
  RecordType rtSampleRequest = [SELECT Id FROM RecordType WHERE DeveloperName = 'EMEA_SU_Sample_Request' AND SObjectType='Sample_Request__c' Limit 1];

  //create account
  Account oTestAccount = new Account(
    Name = 'SC Test Account 1',
    RecordTypeId = rtAccount.Id,
    Legacy_system_id__c = 'UNKGD12345678'  
  );
  try {
    insert oTestAccount;
  } catch(exception e) {
    system.debug('ERROR -- could not create test account.');
  }

  //create user -- with ref to account
  User oTestUser = new User(
    FirstName = 'SCTest',
    LastName = 'User1',
    Personal_account__c = oTestAccount.Legacy_system_id__c,
    ProfileId = pUserProfile.Id,
    Username = 'sctest@aplace.com.dev1',
    Email = 'samantha.cardinali@bausch.com',
    Alias = 'sctest1',
    CommunityNickname = 'sctestfromaplacedev1',
    TimeZoneSidKey = 'America/Los_Angeles',
    LocaleSidKey = 'en_US',
    LanguageLocaleKey = 'en_US',
    EmailEncodingKey = 'UTF-8'
  );
  try {
    insert oTestUser;
  } catch(exception e) {
    system.debug('ERROR -- could not create test user.');
  }
  
  system.runas(oTestUser) {
    //create sample request
    Sample_request__c oTestSampleRequest = new Sample_request__c(
      RecordTypeId = rtSampleRequest.Id,
      Frequency__c = 'Weekly',
      Request_status__c = 'New',
      Courier__c = 'ParcelForce',
      Submit_for_approval__c = False
    );
    try {
      insert oTestSampleRequest;
    } catch(exception e) {
      system.debug('ERROR -- could not create test sample request.');
    }
  
    //check that tm account is populated
    //Sample_request__c sInsertedSampleRequest = [Select Id, Territory_Manager_Account__c From Sample_request__c Where Id = :oTestSampleRequest.Id];
  }
  
  //remove the account reference
  oTestUser.Personal_account__c = '';
  try {
    update oTestUser;
  } catch(exception e) {
    system.debug('ERROR -- could not create test sample request.');
  }

  //generate the error for users without home account set
  system.runas(oTestUser) {
    //create sample request
    Sample_request__c oTestSampleRequest2 = new Sample_request__c(
      RecordTypeId = rtSampleRequest.Id,
      Frequency__c = 'Weekly',
      Request_status__c = 'New',
      Courier__c = 'ParcelForce',
      Submit_for_approval__c = False
    );
    try {
      insert oTestSampleRequest2;
    } catch(exception e) {
      system.debug('ERROR -- could not create test sample request.');
    }
  }
  
  }
}