B&L QA/objects/Survey_Score__c.object
<CustomObject>
    <description>Capture NPS Willingness to Recommend survey responses</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Scores</relationshipLabel>
        <relationshipName>Survey_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legacy_System_Id__c</fullName>
        <description>[Call_ID]-[Q#]</description>
        <externalId>true</externalId>
        <inlineHelpText>[Call_ID]-[Question]</inlineHelpText>
        <label>Legacy System Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Survey Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>On a scale of 0-10,  how likely are you to recommend Bausch + Lomb to a friend or colleague ?</fullName>
                </value>
                <value>
                    <fullName>Q1-CS Performance</fullName>
                </value>
                <value>
                    <fullName>Q2-Easy to do business with</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Reason__c</fullName>
        <label>Customer Feedback</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Score__c</fullName>
        <label>Survey Score</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Source__c</fullName>
        <label>Survey Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CF Phone Survey</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Score</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Survey Score Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B&L QA/classes/TrgSurveyScores_BI_setCSSpecialist.cls
/**
* 
*   Test class for trigger "surveyScores_BI_setCSSpecialist"
* 
*    Author         |Author-Email                   |Date       |Comment
*    ---------------|-------------------------------|-----------|--------------------------------------------------
*    S Cardinali    |samantha.cardinali@bausch.com  |13.07.2011 |First draft
*
*/
@isTest
private class TrgSurveyScores_BI_setCSSpecialist {
  static testMethod void testSurveyScores_BI_setCSSpecialist() {
  
  ID rtShipToAcct = ClsUtility.getRecordTypeId('Account','Ship To Account');
  RecordType rtEMEASurvey = [SELECT Id FROM RecordType WHERE SObjectType = 'Survey_score__c' AND Name = 'EMEA Survey Record'];
  Profile upCSSRep = [SELECT Id FROM profile WHERE name ='EMEACSS: Customer Service Rep' Limit 1];
  //Create account
  Account oAccount = new Account(Name = 'SCTestAcct12345', recordtypeid = rtShipToAcct, SETID__c = 'UNKGD', Ship_to_id__c='13245678', Legacy_system_id__c = 'UNKGD13245678');
  insert oAccount;
  //Create user
  User uCS = new User(alias = 'allbus', 
                             email='allbus@testorg.com', 
                             emailencodingkey='UTF-8',
                             lastname='Testing',
                             languagelocalekey='en_US', 
                             localesidkey='en_US', 
                             profileid = upCSSRep.Id, 
                             timezonesidkey='America/Los_Angeles',
                             username='allbus@testorg.com');  
   insert uCS;
   //Add CS user to account team
   AccountTeamMember oActMbr = new AccountTeamMember(UserId=uCS.Id,AccountId=oAccount.Id,TeamMemberRole='CS Specialist');
   insert oActMbr;
   AccountShare oActShr = new AccountShare(UserOrGroupId=uCS.Id,AccountId=oAccount.Id,AccountAccessLevel='EDIT',CaseAccessLevel='Edit',OpportunityAccessLevel='None');
   insert oActShr;
   //Run as
   System.runAs(uCS) {
       //Insert Survey Score  
       Survey_score__c newSS = new Survey_score__c(Account_Name__c=oAccount.Id,
                                                   Survey_date__c=System.Today(),
                                                   Survey_question__c='Q1-CS Performance',
                                                   Survey_reason__c='Test text',
                                                   Survey_score__c='5',
                                                   Survey_source__c='Manual',
                                                   RecordType = rtEMEASurvey);
       insert newSS; 
   }
  
  }
 }